// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/audit.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ActorUserId    string                 `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	ActorEmail     string                 `protobuf:"bytes,4,opt,name=actor_email,json=actorEmail,proto3" json:"actor_email,omitempty"`
	Action         string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ResourceType   string                 `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId     string                 `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	IpAddress      string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent      string                 `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp      int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_geoquerry_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditRecord) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AuditRecord) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *AuditRecord) GetActorEmail() string {
	if x != nil {
		return x.ActorEmail
	}
	return ""
}

func (x *AuditRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditRecord) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditRecord) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditRecord) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditRecord) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ListAuditLogsRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	OrganizationId string                   `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ResourceType   string                   `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // Optional filter
	Action         string                   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                 // Optional filter
	Pagination     *CursorPaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_geoquerry_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditLogsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListAuditLogsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListAuditLogsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAuditLogsRequest) GetPagination() *CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAuditLogsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Logs          []*AuditRecord            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Pagination    *CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsResponse) Reset() {
	*x = ListAuditLogsResponse{}
	mi := &file_geoquerry_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsResponse) ProtoMessage() {}

func (x *ListAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuditLogsResponse) GetLogs() []*AuditRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ListAuditLogsResponse) GetPagination() *CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_geoquerry_v1_audit_proto protoreflect.FileDescriptor

const file_geoquerry_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x18geoquerry/v1/audit.proto\x12\fgeoquerry.v1\x1a\x19geoquerry/v1/common.proto\"\xc7\x03\n" +
	"\vAuditRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vactor_email\x18\x04 \x01(\tR\n" +
	"actorEmail\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x06 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\x12C\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2'.geoquerry.v1.AuditRecord.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\x14ListAuditLogsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12E\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2%.geoquerry.v1.CursorPaginationRequestR\n" +
	"pagination\"\x8e\x01\n" +
	"\x15ListAuditLogsResponse\x12-\n" +
	"\x04logs\x18\x01 \x03(\v2\x19.geoquerry.v1.AuditRecordR\x04logs\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.geoquerry.v1.CursorPaginationResponseR\n" +
	"pagination2h\n" +
	"\fAuditService\x12X\n" +
	"\rListAuditLogs\x12\".geoquerry.v1.ListAuditLogsRequest\x1a#.geoquerry.v1.ListAuditLogsResponseBLZJgitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1;geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_audit_proto_rawDescOnce sync.Once
	file_geoquerry_v1_audit_proto_rawDescData []byte
)

func file_geoquerry_v1_audit_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_audit_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_audit_proto_rawDesc), len(file_geoquerry_v1_audit_proto_rawDesc)))
	})
	return file_geoquerry_v1_audit_proto_rawDescData
}

var file_geoquerry_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_geoquerry_v1_audit_proto_goTypes = []any{
	(*AuditRecord)(nil),              // 0: geoquerry.v1.AuditRecord
	(*ListAuditLogsRequest)(nil),     // 1: geoquerry.v1.ListAuditLogsRequest
	(*ListAuditLogsResponse)(nil),    // 2: geoquerry.v1.ListAuditLogsResponse
	nil,                              // 3: geoquerry.v1.AuditRecord.MetadataEntry
	(*CursorPaginationRequest)(nil),  // 4: geoquerry.v1.CursorPaginationRequest
	(*CursorPaginationResponse)(nil), // 5: geoquerry.v1.CursorPaginationResponse
}
var file_geoquerry_v1_audit_proto_depIdxs = []int32{
	3, // 0: geoquerry.v1.AuditRecord.metadata:type_name -> geoquerry.v1.AuditRecord.MetadataEntry
	4, // 1: geoquerry.v1.ListAuditLogsRequest.pagination:type_name -> geoquerry.v1.CursorPaginationRequest
	0, // 2: geoquerry.v1.ListAuditLogsResponse.logs:type_name -> geoquerry.v1.AuditRecord
	5, // 3: geoquerry.v1.ListAuditLogsResponse.pagination:type_name -> geoquerry.v1.CursorPaginationResponse
	1, // 4: geoquerry.v1.AuditService.ListAuditLogs:input_type -> geoquerry.v1.ListAuditLogsRequest
	2, // 5: geoquerry.v1.AuditService.ListAuditLogs:output_type -> geoquerry.v1.ListAuditLogsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_audit_proto_init() }
func file_geoquerry_v1_audit_proto_init() {
	if File_geoquerry_v1_audit_proto != nil {
		return
	}
	file_geoquerry_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_audit_proto_rawDesc), len(file_geoquerry_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geoquerry_v1_audit_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_audit_proto_depIdxs,
		MessageInfos:      file_geoquerry_v1_audit_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_audit_proto = out.File
	file_geoquerry_v1_audit_proto_goTypes = nil
	file_geoquerry_v1_audit_proto_depIdxs = nil
}
