// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/auth.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeAssertionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InternalAssertion string                 `protobuf:"bytes,1,opt,name=internal_assertion,json=internalAssertion,proto3" json:"internal_assertion,omitempty"` // Ed25519-signed compact token from Next.js BFF
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExchangeAssertionRequest) Reset() {
	*x = ExchangeAssertionRequest{}
	mi := &file_geoquerry_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAssertionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAssertionRequest) ProtoMessage() {}

func (x *ExchangeAssertionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAssertionRequest.ProtoReflect.Descriptor instead.
func (*ExchangeAssertionRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeAssertionRequest) GetInternalAssertion() string {
	if x != nil {
		return x.InternalAssertion
	}
	return ""
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_geoquerry_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type ExchangeAssertionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	SudoActive    bool                   `protobuf:"varint,3,opt,name=sudo_active,json=sudoActive,proto3" json:"sudo_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeAssertionResponse) Reset() {
	*x = ExchangeAssertionResponse{}
	mi := &file_geoquerry_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAssertionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAssertionResponse) ProtoMessage() {}

func (x *ExchangeAssertionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAssertionResponse.ProtoReflect.Descriptor instead.
func (*ExchangeAssertionResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeAssertionResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ExchangeAssertionResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ExchangeAssertionResponse) GetSudoActive() bool {
	if x != nil {
		return x.SudoActive
	}
	return false
}

type VerifySudoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`                 // Password challenge
	TotpCode      string                 `protobuf:"bytes,2,opt,name=totp_code,json=totpCode,proto3" json:"totp_code,omitempty"` // Optional TOTP 6-digit code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySudoRequest) Reset() {
	*x = VerifySudoRequest{}
	mi := &file_geoquerry_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySudoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySudoRequest) ProtoMessage() {}

func (x *VerifySudoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySudoRequest.ProtoReflect.Descriptor instead.
func (*VerifySudoRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *VerifySudoRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *VerifySudoRequest) GetTotpCode() string {
	if x != nil {
		return x.TotpCode
	}
	return ""
}

type VerifySudoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SudoExpiresAt int64                  `protobuf:"varint,2,opt,name=sudo_expires_at,json=sudoExpiresAt,proto3" json:"sudo_expires_at,omitempty"` // Epoch timestamp (now + 15 min)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySudoResponse) Reset() {
	*x = VerifySudoResponse{}
	mi := &file_geoquerry_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySudoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySudoResponse) ProtoMessage() {}

func (x *VerifySudoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySudoResponse.ProtoReflect.Descriptor instead.
func (*VerifySudoResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifySudoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifySudoResponse) GetSudoExpiresAt() int64 {
	if x != nil {
		return x.SudoExpiresAt
	}
	return 0
}

type GetSessionContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionContextRequest) Reset() {
	*x = GetSessionContextRequest{}
	mi := &file_geoquerry_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionContextRequest) ProtoMessage() {}

func (x *GetSessionContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionContextRequest.ProtoReflect.Descriptor instead.
func (*GetSessionContextRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_auth_proto_rawDescGZIP(), []int{5}
}

type GetSessionContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SudoActive    bool                   `protobuf:"varint,2,opt,name=sudo_active,json=sudoActive,proto3" json:"sudo_active,omitempty"`
	SudoExpiresAt int64                  `protobuf:"varint,3,opt,name=sudo_expires_at,json=sudoExpiresAt,proto3" json:"sudo_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionContextResponse) Reset() {
	*x = GetSessionContextResponse{}
	mi := &file_geoquerry_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionContextResponse) ProtoMessage() {}

func (x *GetSessionContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionContextResponse.ProtoReflect.Descriptor instead.
func (*GetSessionContextResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionContextResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetSessionContextResponse) GetSudoActive() bool {
	if x != nil {
		return x.SudoActive
	}
	return false
}

func (x *GetSessionContextResponse) GetSudoExpiresAt() int64 {
	if x != nil {
		return x.SudoExpiresAt
	}
	return 0
}

var File_geoquerry_v1_auth_proto protoreflect.FileDescriptor

const file_geoquerry_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x17geoquerry/v1/auth.proto\x12\fgeoquerry.v1\"I\n" +
	"\x18ExchangeAssertionRequest\x12-\n" +
	"\x12internal_assertion\x18\x01 \x01(\tR\x11internalAssertion\"~\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"\x8c\x01\n" +
	"\x19ExchangeAssertionResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.geoquerry.v1.UserProfileR\x04user\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x1f\n" +
	"\vsudo_active\x18\x03 \x01(\bR\n" +
	"sudoActive\"L\n" +
	"\x11VerifySudoRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1b\n" +
	"\ttotp_code\x18\x02 \x01(\tR\btotpCode\"V\n" +
	"\x12VerifySudoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fsudo_expires_at\x18\x02 \x01(\x03R\rsudoExpiresAt\"\x1a\n" +
	"\x18GetSessionContextRequest\"\x93\x01\n" +
	"\x19GetSessionContextResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.geoquerry.v1.UserProfileR\x04user\x12\x1f\n" +
	"\vsudo_active\x18\x02 \x01(\bR\n" +
	"sudoActive\x12&\n" +
	"\x0fsudo_expires_at\x18\x03 \x01(\x03R\rsudoExpiresAt2\xaa\x02\n" +
	"\vAuthService\x12d\n" +
	"\x11ExchangeAssertion\x12&.geoquerry.v1.ExchangeAssertionRequest\x1a'.geoquerry.v1.ExchangeAssertionResponse\x12O\n" +
	"\n" +
	"VerifySudo\x12\x1f.geoquerry.v1.VerifySudoRequest\x1a .geoquerry.v1.VerifySudoResponse\x12d\n" +
	"\x11GetSessionContext\x12&.geoquerry.v1.GetSessionContextRequest\x1a'.geoquerry.v1.GetSessionContextResponseBLZJgitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1;geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_auth_proto_rawDescOnce sync.Once
	file_geoquerry_v1_auth_proto_rawDescData []byte
)

func file_geoquerry_v1_auth_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_auth_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_auth_proto_rawDesc), len(file_geoquerry_v1_auth_proto_rawDesc)))
	})
	return file_geoquerry_v1_auth_proto_rawDescData
}

var file_geoquerry_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_geoquerry_v1_auth_proto_goTypes = []any{
	(*ExchangeAssertionRequest)(nil),  // 0: geoquerry.v1.ExchangeAssertionRequest
	(*UserProfile)(nil),               // 1: geoquerry.v1.UserProfile
	(*ExchangeAssertionResponse)(nil), // 2: geoquerry.v1.ExchangeAssertionResponse
	(*VerifySudoRequest)(nil),         // 3: geoquerry.v1.VerifySudoRequest
	(*VerifySudoResponse)(nil),        // 4: geoquerry.v1.VerifySudoResponse
	(*GetSessionContextRequest)(nil),  // 5: geoquerry.v1.GetSessionContextRequest
	(*GetSessionContextResponse)(nil), // 6: geoquerry.v1.GetSessionContextResponse
}
var file_geoquerry_v1_auth_proto_depIdxs = []int32{
	1, // 0: geoquerry.v1.ExchangeAssertionResponse.user:type_name -> geoquerry.v1.UserProfile
	1, // 1: geoquerry.v1.GetSessionContextResponse.user:type_name -> geoquerry.v1.UserProfile
	0, // 2: geoquerry.v1.AuthService.ExchangeAssertion:input_type -> geoquerry.v1.ExchangeAssertionRequest
	3, // 3: geoquerry.v1.AuthService.VerifySudo:input_type -> geoquerry.v1.VerifySudoRequest
	5, // 4: geoquerry.v1.AuthService.GetSessionContext:input_type -> geoquerry.v1.GetSessionContextRequest
	2, // 5: geoquerry.v1.AuthService.ExchangeAssertion:output_type -> geoquerry.v1.ExchangeAssertionResponse
	4, // 6: geoquerry.v1.AuthService.VerifySudo:output_type -> geoquerry.v1.VerifySudoResponse
	6, // 7: geoquerry.v1.AuthService.GetSessionContext:output_type -> geoquerry.v1.GetSessionContextResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_auth_proto_init() }
func file_geoquerry_v1_auth_proto_init() {
	if File_geoquerry_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_auth_proto_rawDesc), len(file_geoquerry_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geoquerry_v1_auth_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_auth_proto_depIdxs,
		MessageInfos:      file_geoquerry_v1_auth_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_auth_proto = out.File
	file_geoquerry_v1_auth_proto_goTypes = nil
	file_geoquerry_v1_auth_proto_depIdxs = nil
}
