// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/billing.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BillingProvider int32

const (
	BillingProvider_BILLING_PROVIDER_UNSPECIFIED BillingProvider = 0
	BillingProvider_BILLING_PROVIDER_MPESA       BillingProvider = 1
	BillingProvider_BILLING_PROVIDER_STRIPE      BillingProvider = 2
)

// Enum value maps for BillingProvider.
var (
	BillingProvider_name = map[int32]string{
		0: "BILLING_PROVIDER_UNSPECIFIED",
		1: "BILLING_PROVIDER_MPESA",
		2: "BILLING_PROVIDER_STRIPE",
	}
	BillingProvider_value = map[string]int32{
		"BILLING_PROVIDER_UNSPECIFIED": 0,
		"BILLING_PROVIDER_MPESA":       1,
		"BILLING_PROVIDER_STRIPE":      2,
	}
)

func (x BillingProvider) Enum() *BillingProvider {
	p := new(BillingProvider)
	*p = x
	return p
}

func (x BillingProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BillingProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_geoquerry_v1_billing_proto_enumTypes[0].Descriptor()
}

func (BillingProvider) Type() protoreflect.EnumType {
	return &file_geoquerry_v1_billing_proto_enumTypes[0]
}

func (x BillingProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BillingProvider.Descriptor instead.
func (BillingProvider) EnumDescriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{0}
}

type SubscriptionStatus int32

const (
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED SubscriptionStatus = 0
	SubscriptionStatus_SUBSCRIPTION_STATUS_INACTIVE    SubscriptionStatus = 1
	SubscriptionStatus_SUBSCRIPTION_STATUS_TRIALING    SubscriptionStatus = 2
	SubscriptionStatus_SUBSCRIPTION_STATUS_ACTIVE      SubscriptionStatus = 3
	SubscriptionStatus_SUBSCRIPTION_STATUS_PAST_DUE    SubscriptionStatus = 4
	SubscriptionStatus_SUBSCRIPTION_STATUS_CANCELED    SubscriptionStatus = 5
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNPAID      SubscriptionStatus = 6
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "SUBSCRIPTION_STATUS_UNSPECIFIED",
		1: "SUBSCRIPTION_STATUS_INACTIVE",
		2: "SUBSCRIPTION_STATUS_TRIALING",
		3: "SUBSCRIPTION_STATUS_ACTIVE",
		4: "SUBSCRIPTION_STATUS_PAST_DUE",
		5: "SUBSCRIPTION_STATUS_CANCELED",
		6: "SUBSCRIPTION_STATUS_UNPAID",
	}
	SubscriptionStatus_value = map[string]int32{
		"SUBSCRIPTION_STATUS_UNSPECIFIED": 0,
		"SUBSCRIPTION_STATUS_INACTIVE":    1,
		"SUBSCRIPTION_STATUS_TRIALING":    2,
		"SUBSCRIPTION_STATUS_ACTIVE":      3,
		"SUBSCRIPTION_STATUS_PAST_DUE":    4,
		"SUBSCRIPTION_STATUS_CANCELED":    5,
		"SUBSCRIPTION_STATUS_UNPAID":      6,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_geoquerry_v1_billing_proto_enumTypes[1].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_geoquerry_v1_billing_proto_enumTypes[1]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{1}
}

type PlanItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlanId           string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AmountMinorUnits int64                  `protobuf:"varint,4,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"` // Minor units (e.g. 500000 = 5,000 KES, 4900 = 49 USD)
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                                            // "KES" or "USD"
	Interval         string                 `protobuf:"bytes,6,opt,name=interval,proto3" json:"interval,omitempty"`                                            // "month" or "year"
	Features         []string               `protobuf:"bytes,7,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlanItem) Reset() {
	*x = PlanItem{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanItem) ProtoMessage() {}

func (x *PlanItem) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanItem.ProtoReflect.Descriptor instead.
func (*PlanItem) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *PlanItem) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlanItem) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

func (x *PlanItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PlanItem) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *PlanItem) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type OrganizationSubscription struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PlanId            string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Status            SubscriptionStatus     `protobuf:"varint,3,opt,name=status,proto3,enum=geoquerry.v1.SubscriptionStatus" json:"status,omitempty"`
	CurrentPeriodEnd  int64                  `protobuf:"varint,4,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	CancelAtPeriodEnd bool                   `protobuf:"varint,5,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"`
	Entitlements      []string               `protobuf:"bytes,6,rep,name=entitlements,proto3" json:"entitlements,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrganizationSubscription) Reset() {
	*x = OrganizationSubscription{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationSubscription) ProtoMessage() {}

func (x *OrganizationSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationSubscription.ProtoReflect.Descriptor instead.
func (*OrganizationSubscription) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *OrganizationSubscription) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationSubscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *OrganizationSubscription) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *OrganizationSubscription) GetCurrentPeriodEnd() int64 {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return 0
}

func (x *OrganizationSubscription) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *OrganizationSubscription) GetEntitlements() []string {
	if x != nil {
		return x.Entitlements
	}
	return nil
}

type GetPriceCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"` // Optional filter ("KES" or "USD")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceCatalogRequest) Reset() {
	*x = GetPriceCatalogRequest{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceCatalogRequest) ProtoMessage() {}

func (x *GetPriceCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetPriceCatalogRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetPriceCatalogRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetPriceCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*PlanItem            `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceCatalogResponse) Reset() {
	*x = GetPriceCatalogResponse{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceCatalogResponse) ProtoMessage() {}

func (x *GetPriceCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetPriceCatalogResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetPriceCatalogResponse) GetPlans() []*PlanItem {
	if x != nil {
		return x.Plans
	}
	return nil
}

type InitiateMpesaStkPushRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PlanId         string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PhoneNumber    string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // E.164 or Kenyan local format (e.g. 254712345678)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateMpesaStkPushRequest) Reset() {
	*x = InitiateMpesaStkPushRequest{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMpesaStkPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMpesaStkPushRequest) ProtoMessage() {}

func (x *InitiateMpesaStkPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMpesaStkPushRequest.ProtoReflect.Descriptor instead.
func (*InitiateMpesaStkPushRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *InitiateMpesaStkPushRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *InitiateMpesaStkPushRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *InitiateMpesaStkPushRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type InitiateMpesaStkPushResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentAttemptId string                 `protobuf:"bytes,1,opt,name=payment_attempt_id,json=paymentAttemptId,proto3" json:"payment_attempt_id,omitempty"`
	CustomerMessage  string                 `protobuf:"bytes,2,opt,name=customer_message,json=customerMessage,proto3" json:"customer_message,omitempty"`
	ServerTime       int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitiateMpesaStkPushResponse) Reset() {
	*x = InitiateMpesaStkPushResponse{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMpesaStkPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMpesaStkPushResponse) ProtoMessage() {}

func (x *InitiateMpesaStkPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMpesaStkPushResponse.ProtoReflect.Descriptor instead.
func (*InitiateMpesaStkPushResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *InitiateMpesaStkPushResponse) GetPaymentAttemptId() string {
	if x != nil {
		return x.PaymentAttemptId
	}
	return ""
}

func (x *InitiateMpesaStkPushResponse) GetCustomerMessage() string {
	if x != nil {
		return x.CustomerMessage
	}
	return ""
}

func (x *InitiateMpesaStkPushResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type CreateStripeCheckoutSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PlanId         string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	SuccessUrl     string                 `protobuf:"bytes,3,opt,name=success_url,json=successUrl,proto3" json:"success_url,omitempty"`
	CancelUrl      string                 `protobuf:"bytes,4,opt,name=cancel_url,json=cancelUrl,proto3" json:"cancel_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateStripeCheckoutSessionRequest) Reset() {
	*x = CreateStripeCheckoutSessionRequest{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStripeCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStripeCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateStripeCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStripeCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateStripeCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *CreateStripeCheckoutSessionRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateStripeCheckoutSessionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateStripeCheckoutSessionRequest) GetSuccessUrl() string {
	if x != nil {
		return x.SuccessUrl
	}
	return ""
}

func (x *CreateStripeCheckoutSessionRequest) GetCancelUrl() string {
	if x != nil {
		return x.CancelUrl
	}
	return ""
}

type CreateStripeCheckoutSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckoutSessionId string                 `protobuf:"bytes,1,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	CheckoutUrl       string                 `protobuf:"bytes,2,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateStripeCheckoutSessionResponse) Reset() {
	*x = CreateStripeCheckoutSessionResponse{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStripeCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStripeCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateStripeCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStripeCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateStripeCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *CreateStripeCheckoutSessionResponse) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

func (x *CreateStripeCheckoutSessionResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type GetSubscriptionStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSubscriptionStatusRequest) Reset() {
	*x = GetSubscriptionStatusRequest{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionStatusRequest) ProtoMessage() {}

func (x *GetSubscriptionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionStatusRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{8}
}

func (x *GetSubscriptionStatusRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetSubscriptionStatusResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Subscription  *OrganizationSubscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionStatusResponse) Reset() {
	*x = GetSubscriptionStatusResponse{}
	mi := &file_geoquerry_v1_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionStatusResponse) ProtoMessage() {}

func (x *GetSubscriptionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionStatusResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_billing_proto_rawDescGZIP(), []int{9}
}

func (x *GetSubscriptionStatusResponse) GetSubscription() *OrganizationSubscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

var File_geoquerry_v1_billing_proto protoreflect.FileDescriptor

const file_geoquerry_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x1ageoquerry/v1/billing.proto\x12\fgeoquerry.v1\"\xdb\x01\n" +
	"\bPlanItem\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x12amount_minor_units\x18\x04 \x01(\x03R\x10amountMinorUnits\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\tR\binterval\x12\x1a\n" +
	"\bfeatures\x18\a \x03(\tR\bfeatures\"\x99\x02\n" +
	"\x18OrganizationSubscription\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .geoquerry.v1.SubscriptionStatusR\x06status\x12,\n" +
	"\x12current_period_end\x18\x04 \x01(\x03R\x10currentPeriodEnd\x12/\n" +
	"\x14cancel_at_period_end\x18\x05 \x01(\bR\x11cancelAtPeriodEnd\x12\"\n" +
	"\fentitlements\x18\x06 \x03(\tR\fentitlements\"4\n" +
	"\x16GetPriceCatalogRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\"G\n" +
	"\x17GetPriceCatalogResponse\x12,\n" +
	"\x05plans\x18\x01 \x03(\v2\x16.geoquerry.v1.PlanItemR\x05plans\"\x82\x01\n" +
	"\x1bInitiateMpesaStkPushRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\"\x98\x01\n" +
	"\x1cInitiateMpesaStkPushResponse\x12,\n" +
	"\x12payment_attempt_id\x18\x01 \x01(\tR\x10paymentAttemptId\x12)\n" +
	"\x10customer_message\x18\x02 \x01(\tR\x0fcustomerMessage\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\"\xa6\x01\n" +
	"\"CreateStripeCheckoutSessionRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1f\n" +
	"\vsuccess_url\x18\x03 \x01(\tR\n" +
	"successUrl\x12\x1d\n" +
	"\n" +
	"cancel_url\x18\x04 \x01(\tR\tcancelUrl\"x\n" +
	"#CreateStripeCheckoutSessionResponse\x12.\n" +
	"\x13checkout_session_id\x18\x01 \x01(\tR\x11checkoutSessionId\x12!\n" +
	"\fcheckout_url\x18\x02 \x01(\tR\vcheckoutUrl\"G\n" +
	"\x1cGetSubscriptionStatusRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"k\n" +
	"\x1dGetSubscriptionStatusResponse\x12J\n" +
	"\fsubscription\x18\x01 \x01(\v2&.geoquerry.v1.OrganizationSubscriptionR\fsubscription*l\n" +
	"\x0fBillingProvider\x12 \n" +
	"\x1cBILLING_PROVIDER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BILLING_PROVIDER_MPESA\x10\x01\x12\x1b\n" +
	"\x17BILLING_PROVIDER_STRIPE\x10\x02*\x81\x02\n" +
	"\x12SubscriptionStatus\x12#\n" +
	"\x1fSUBSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_INACTIVE\x10\x01\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_TRIALING\x10\x02\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_ACTIVE\x10\x03\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_PAST_DUE\x10\x04\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_CANCELED\x10\x05\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_UNPAID\x10\x062\xd6\x03\n" +
	"\x0eBillingService\x12^\n" +
	"\x0fGetPriceCatalog\x12$.geoquerry.v1.GetPriceCatalogRequest\x1a%.geoquerry.v1.GetPriceCatalogResponse\x12m\n" +
	"\x14InitiateMpesaStkPush\x12).geoquerry.v1.InitiateMpesaStkPushRequest\x1a*.geoquerry.v1.InitiateMpesaStkPushResponse\x12\x82\x01\n" +
	"\x1bCreateStripeCheckoutSession\x120.geoquerry.v1.CreateStripeCheckoutSessionRequest\x1a1.geoquerry.v1.CreateStripeCheckoutSessionResponse\x12p\n" +
	"\x15GetSubscriptionStatus\x12*.geoquerry.v1.GetSubscriptionStatusRequest\x1a+.geoquerry.v1.GetSubscriptionStatusResponseBLZJgitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1;geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_billing_proto_rawDescOnce sync.Once
	file_geoquerry_v1_billing_proto_rawDescData []byte
)

func file_geoquerry_v1_billing_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_billing_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_billing_proto_rawDesc), len(file_geoquerry_v1_billing_proto_rawDesc)))
	})
	return file_geoquerry_v1_billing_proto_rawDescData
}

var file_geoquerry_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_geoquerry_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_geoquerry_v1_billing_proto_goTypes = []any{
	(BillingProvider)(0),                        // 0: geoquerry.v1.BillingProvider
	(SubscriptionStatus)(0),                     // 1: geoquerry.v1.SubscriptionStatus
	(*PlanItem)(nil),                            // 2: geoquerry.v1.PlanItem
	(*OrganizationSubscription)(nil),            // 3: geoquerry.v1.OrganizationSubscription
	(*GetPriceCatalogRequest)(nil),              // 4: geoquerry.v1.GetPriceCatalogRequest
	(*GetPriceCatalogResponse)(nil),             // 5: geoquerry.v1.GetPriceCatalogResponse
	(*InitiateMpesaStkPushRequest)(nil),         // 6: geoquerry.v1.InitiateMpesaStkPushRequest
	(*InitiateMpesaStkPushResponse)(nil),        // 7: geoquerry.v1.InitiateMpesaStkPushResponse
	(*CreateStripeCheckoutSessionRequest)(nil),  // 8: geoquerry.v1.CreateStripeCheckoutSessionRequest
	(*CreateStripeCheckoutSessionResponse)(nil), // 9: geoquerry.v1.CreateStripeCheckoutSessionResponse
	(*GetSubscriptionStatusRequest)(nil),        // 10: geoquerry.v1.GetSubscriptionStatusRequest
	(*GetSubscriptionStatusResponse)(nil),       // 11: geoquerry.v1.GetSubscriptionStatusResponse
}
var file_geoquerry_v1_billing_proto_depIdxs = []int32{
	1,  // 0: geoquerry.v1.OrganizationSubscription.status:type_name -> geoquerry.v1.SubscriptionStatus
	2,  // 1: geoquerry.v1.GetPriceCatalogResponse.plans:type_name -> geoquerry.v1.PlanItem
	3,  // 2: geoquerry.v1.GetSubscriptionStatusResponse.subscription:type_name -> geoquerry.v1.OrganizationSubscription
	4,  // 3: geoquerry.v1.BillingService.GetPriceCatalog:input_type -> geoquerry.v1.GetPriceCatalogRequest
	6,  // 4: geoquerry.v1.BillingService.InitiateMpesaStkPush:input_type -> geoquerry.v1.InitiateMpesaStkPushRequest
	8,  // 5: geoquerry.v1.BillingService.CreateStripeCheckoutSession:input_type -> geoquerry.v1.CreateStripeCheckoutSessionRequest
	10, // 6: geoquerry.v1.BillingService.GetSubscriptionStatus:input_type -> geoquerry.v1.GetSubscriptionStatusRequest
	5,  // 7: geoquerry.v1.BillingService.GetPriceCatalog:output_type -> geoquerry.v1.GetPriceCatalogResponse
	7,  // 8: geoquerry.v1.BillingService.InitiateMpesaStkPush:output_type -> geoquerry.v1.InitiateMpesaStkPushResponse
	9,  // 9: geoquerry.v1.BillingService.CreateStripeCheckoutSession:output_type -> geoquerry.v1.CreateStripeCheckoutSessionResponse
	11, // 10: geoquerry.v1.BillingService.GetSubscriptionStatus:output_type -> geoquerry.v1.GetSubscriptionStatusResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_billing_proto_init() }
func file_geoquerry_v1_billing_proto_init() {
	if File_geoquerry_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_billing_proto_rawDesc), len(file_geoquerry_v1_billing_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geoquerry_v1_billing_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_billing_proto_depIdxs,
		EnumInfos:         file_geoquerry_v1_billing_proto_enumTypes,
		MessageInfos:      file_geoquerry_v1_billing_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_billing_proto = out.File
	file_geoquerry_v1_billing_proto_goTypes = nil
	file_geoquerry_v1_billing_proto_depIdxs = nil
}
