// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/common.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorInfo provides structured, machine-readable diagnostics attached to ConnectRPC errors.
// Prevents internal SQL, path, or stack trace disclosure.
type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`             // e.g. "GEO_PERMISSION_DENIED", "GEO_SUDO_REQUIRED", "GEO_TENANT_NOT_FOUND"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // Safe, sanitized human-readable message
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Trace correlation identifier
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_geoquerry_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ErrorInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CursorPaginationRequest standardizes opaque cursor pagination across collections.
type CursorPaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // Opaque base64 cursor representing (timestamp, id)
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Maximum items to return (clamped between 1 and 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPaginationRequest) Reset() {
	*x = CursorPaginationRequest{}
	mi := &file_geoquerry_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPaginationRequest) ProtoMessage() {}

func (x *CursorPaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPaginationRequest.ProtoReflect.Descriptor instead.
func (*CursorPaginationRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *CursorPaginationRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *CursorPaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// CursorPaginationResponse returns next cursor info.
type CursorPaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Empty if end of collection reached
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	TotalEstimate int64                  `protobuf:"varint,3,opt,name=total_estimate,json=totalEstimate,proto3" json:"total_estimate,omitempty"` // Optional non-exact count estimate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPaginationResponse) Reset() {
	*x = CursorPaginationResponse{}
	mi := &file_geoquerry_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPaginationResponse) ProtoMessage() {}

func (x *CursorPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPaginationResponse.ProtoReflect.Descriptor instead.
func (*CursorPaginationResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *CursorPaginationResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *CursorPaginationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *CursorPaginationResponse) GetTotalEstimate() int64 {
	if x != nil {
		return x.TotalEstimate
	}
	return 0
}

var File_geoquerry_v1_common_proto protoreflect.FileDescriptor

const file_geoquerry_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19geoquerry/v1/common.proto\x12\fgeoquerry.v1\"\xeb\x01\n" +
	"\tErrorInfo\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.geoquerry.v1.ErrorInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x17CursorPaginationRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"}\n" +
	"\x18CursorPaginationResponse\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12%\n" +
	"\x0etotal_estimate\x18\x03 \x01(\x03R\rtotalEstimateBLZJgitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1;geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_common_proto_rawDescOnce sync.Once
	file_geoquerry_v1_common_proto_rawDescData []byte
)

func file_geoquerry_v1_common_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_common_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_common_proto_rawDesc), len(file_geoquerry_v1_common_proto_rawDesc)))
	})
	return file_geoquerry_v1_common_proto_rawDescData
}

var file_geoquerry_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_geoquerry_v1_common_proto_goTypes = []any{
	(*ErrorInfo)(nil),                // 0: geoquerry.v1.ErrorInfo
	(*CursorPaginationRequest)(nil),  // 1: geoquerry.v1.CursorPaginationRequest
	(*CursorPaginationResponse)(nil), // 2: geoquerry.v1.CursorPaginationResponse
	nil,                              // 3: geoquerry.v1.ErrorInfo.MetadataEntry
}
var file_geoquerry_v1_common_proto_depIdxs = []int32{
	3, // 0: geoquerry.v1.ErrorInfo.metadata:type_name -> geoquerry.v1.ErrorInfo.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_common_proto_init() }
func file_geoquerry_v1_common_proto_init() {
	if File_geoquerry_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_common_proto_rawDesc), len(file_geoquerry_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geoquerry_v1_common_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_common_proto_depIdxs,
		MessageInfos:      file_geoquerry_v1_common_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_common_proto = out.File
	file_geoquerry_v1_common_proto_goTypes = nil
	file_geoquerry_v1_common_proto_depIdxs = nil
}
