// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/geology.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StructuralMeasurement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StationId       string                 `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MeasurementType string                 `protobuf:"bytes,3,opt,name=measurement_type,json=measurementType,proto3" json:"measurement_type,omitempty"`
	Strike          float64                `protobuf:"fixed64,4,opt,name=strike,proto3" json:"strike,omitempty"`
	Dip             float64                `protobuf:"fixed64,5,opt,name=dip,proto3" json:"dip,omitempty"`
	DipDirection    float64                `protobuf:"fixed64,6,opt,name=dip_direction,json=dipDirection,proto3" json:"dip_direction,omitempty"`
	Autocaptured    bool                   `protobuf:"varint,7,opt,name=autocaptured,proto3" json:"autocaptured,omitempty"`
	Trend           float64                `protobuf:"fixed64,8,opt,name=trend,proto3" json:"trend,omitempty"`
	Plunge          float64                `protobuf:"fixed64,9,opt,name=plunge,proto3" json:"plunge,omitempty"`
	Notes           string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted       bool                   `protobuf:"varint,12,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StructuralMeasurement) Reset() {
	*x = StructuralMeasurement{}
	mi := &file_geoquerry_v1_geology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuralMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuralMeasurement) ProtoMessage() {}

func (x *StructuralMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_geology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuralMeasurement.ProtoReflect.Descriptor instead.
func (*StructuralMeasurement) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_geology_proto_rawDescGZIP(), []int{0}
}

func (x *StructuralMeasurement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StructuralMeasurement) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *StructuralMeasurement) GetMeasurementType() string {
	if x != nil {
		return x.MeasurementType
	}
	return ""
}

func (x *StructuralMeasurement) GetStrike() float64 {
	if x != nil {
		return x.Strike
	}
	return 0
}

func (x *StructuralMeasurement) GetDip() float64 {
	if x != nil {
		return x.Dip
	}
	return 0
}

func (x *StructuralMeasurement) GetDipDirection() float64 {
	if x != nil {
		return x.DipDirection
	}
	return 0
}

func (x *StructuralMeasurement) GetAutocaptured() bool {
	if x != nil {
		return x.Autocaptured
	}
	return false
}

func (x *StructuralMeasurement) GetTrend() float64 {
	if x != nil {
		return x.Trend
	}
	return 0
}

func (x *StructuralMeasurement) GetPlunge() float64 {
	if x != nil {
		return x.Plunge
	}
	return 0
}

func (x *StructuralMeasurement) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StructuralMeasurement) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *StructuralMeasurement) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type RockSample struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StationId           string                 `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SampleTag           string                 `protobuf:"bytes,3,opt,name=sample_tag,json=sampleTag,proto3" json:"sample_tag,omitempty"`
	LithologyClass      string                 `protobuf:"bytes,4,opt,name=lithology_class,json=lithologyClass,proto3" json:"lithology_class,omitempty"`
	MineralizationNotes string                 `protobuf:"bytes,5,opt,name=mineralization_notes,json=mineralizationNotes,proto3" json:"mineralization_notes,omitempty"`
	PhotoR2Keys         []string               `protobuf:"bytes,6,rep,name=photo_r2_keys,json=photoR2Keys,proto3" json:"photo_r2_keys,omitempty"`
	AssaysStatus        string                 `protobuf:"bytes,7,opt,name=assays_status,json=assaysStatus,proto3" json:"assays_status,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted           bool                   `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RockSample) Reset() {
	*x = RockSample{}
	mi := &file_geoquerry_v1_geology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RockSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RockSample) ProtoMessage() {}

func (x *RockSample) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_geology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RockSample.ProtoReflect.Descriptor instead.
func (*RockSample) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_geology_proto_rawDescGZIP(), []int{1}
}

func (x *RockSample) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RockSample) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *RockSample) GetSampleTag() string {
	if x != nil {
		return x.SampleTag
	}
	return ""
}

func (x *RockSample) GetLithologyClass() string {
	if x != nil {
		return x.LithologyClass
	}
	return ""
}

func (x *RockSample) GetMineralizationNotes() string {
	if x != nil {
		return x.MineralizationNotes
	}
	return ""
}

func (x *RockSample) GetPhotoR2Keys() []string {
	if x != nil {
		return x.PhotoR2Keys
	}
	return nil
}

func (x *RockSample) GetAssaysStatus() string {
	if x != nil {
		return x.AssaysStatus
	}
	return ""
}

func (x *RockSample) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RockSample) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type Station struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Id              string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId       string                   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Code            string                   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Latitude        float64                  `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float64                  `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Elevation       float64                  `protobuf:"fixed64,7,opt,name=elevation,proto3" json:"elevation,omitempty"`
	GpsAccuracy     float64                  `protobuf:"fixed64,8,opt,name=gps_accuracy,json=gpsAccuracy,proto3" json:"gps_accuracy,omitempty"`
	OutcropExposure string                   `protobuf:"bytes,9,opt,name=outcrop_exposure,json=outcropExposure,proto3" json:"outcrop_exposure,omitempty"`
	Lithology       string                   `protobuf:"bytes,10,opt,name=lithology,proto3" json:"lithology,omitempty"`
	Notes           string                   `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	Measurements    []*StructuralMeasurement `protobuf:"bytes,12,rep,name=measurements,proto3" json:"measurements,omitempty"` //populated by server on pull but ignored on push
	Samples         []*RockSample            `protobuf:"bytes,13,rep,name=samples,proto3" json:"samples,omitempty"`           // this too and the one below
	Vegetation      []*Vegetation            `protobuf:"bytes,14,rep,name=vegetation,proto3" json:"vegetation,omitempty"`
	UpdatedAt       int64                    `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted       bool                     `protobuf:"varint,16,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Station) Reset() {
	*x = Station{}
	mi := &file_geoquerry_v1_geology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Station) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Station) ProtoMessage() {}

func (x *Station) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_geology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Station.ProtoReflect.Descriptor instead.
func (*Station) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_geology_proto_rawDescGZIP(), []int{2}
}

func (x *Station) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Station) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Station) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Station) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Station) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Station) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Station) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

func (x *Station) GetGpsAccuracy() float64 {
	if x != nil {
		return x.GpsAccuracy
	}
	return 0
}

func (x *Station) GetOutcropExposure() string {
	if x != nil {
		return x.OutcropExposure
	}
	return ""
}

func (x *Station) GetLithology() string {
	if x != nil {
		return x.Lithology
	}
	return ""
}

func (x *Station) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Station) GetMeasurements() []*StructuralMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *Station) GetSamples() []*RockSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *Station) GetVegetation() []*Vegetation {
	if x != nil {
		return x.Vegetation
	}
	return nil
}

func (x *Station) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Station) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type BoreholeInterval struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BoreholeId         string                 `protobuf:"bytes,2,opt,name=borehole_id,json=boreholeId,proto3" json:"borehole_id,omitempty"`
	DepthFrom          float64                `protobuf:"fixed64,3,opt,name=depth_from,json=depthFrom,proto3" json:"depth_from,omitempty"`
	DepthTo            float64                `protobuf:"fixed64,4,opt,name=depth_to,json=depthTo,proto3" json:"depth_to,omitempty"`
	Lithology          string                 `protobuf:"bytes,5,opt,name=lithology,proto3" json:"lithology,omitempty"`
	Description        string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	RecoveryPercentage float64                `protobuf:"fixed64,7,opt,name=recovery_percentage,json=recoveryPercentage,proto3" json:"recovery_percentage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BoreholeInterval) Reset() {
	*x = BoreholeInterval{}
	mi := &file_geoquerry_v1_geology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoreholeInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoreholeInterval) ProtoMessage() {}

func (x *BoreholeInterval) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_geology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoreholeInterval.ProtoReflect.Descriptor instead.
func (*BoreholeInterval) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_geology_proto_rawDescGZIP(), []int{3}
}

func (x *BoreholeInterval) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoreholeInterval) GetBoreholeId() string {
	if x != nil {
		return x.BoreholeId
	}
	return ""
}

func (x *BoreholeInterval) GetDepthFrom() float64 {
	if x != nil {
		return x.DepthFrom
	}
	return 0
}

func (x *BoreholeInterval) GetDepthTo() float64 {
	if x != nil {
		return x.DepthTo
	}
	return 0
}

func (x *BoreholeInterval) GetLithology() string {
	if x != nil {
		return x.Lithology
	}
	return ""
}

func (x *BoreholeInterval) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoreholeInterval) GetRecoveryPercentage() float64 {
	if x != nil {
		return x.RecoveryPercentage
	}
	return 0
}

type Borehole struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId          string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	BoreholeCode       string                 `protobuf:"bytes,3,opt,name=borehole_code,json=boreholeCode,proto3" json:"borehole_code,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Latitude           float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude          float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CollarElevation    float64                `protobuf:"fixed64,7,opt,name=collar_elevation,json=collarElevation,proto3" json:"collar_elevation,omitempty"`
	TotalDepthMeters   float64                `protobuf:"fixed64,8,opt,name=total_depth_meters,json=totalDepthMeters,proto3" json:"total_depth_meters,omitempty"`
	WaterStrikeDepth   float64                `protobuf:"fixed64,9,opt,name=water_strike_depth,json=waterStrikeDepth,proto3" json:"water_strike_depth,omitempty"`
	YieldLitersPerHour float64                `protobuf:"fixed64,10,opt,name=yield_liters_per_hour,json=yieldLitersPerHour,proto3" json:"yield_liters_per_hour,omitempty"`
	Intervals          []*BoreholeInterval    `protobuf:"bytes,11,rep,name=intervals,proto3" json:"intervals,omitempty"`
	UpdatedAt          int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted          bool                   `protobuf:"varint,13,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Borehole) Reset() {
	*x = Borehole{}
	mi := &file_geoquerry_v1_geology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Borehole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borehole) ProtoMessage() {}

func (x *Borehole) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_geology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borehole.ProtoReflect.Descriptor instead.
func (*Borehole) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_geology_proto_rawDescGZIP(), []int{4}
}

func (x *Borehole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Borehole) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Borehole) GetBoreholeCode() string {
	if x != nil {
		return x.BoreholeCode
	}
	return ""
}

func (x *Borehole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Borehole) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Borehole) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Borehole) GetCollarElevation() float64 {
	if x != nil {
		return x.CollarElevation
	}
	return 0
}

func (x *Borehole) GetTotalDepthMeters() float64 {
	if x != nil {
		return x.TotalDepthMeters
	}
	return 0
}

func (x *Borehole) GetWaterStrikeDepth() float64 {
	if x != nil {
		return x.WaterStrikeDepth
	}
	return 0
}

func (x *Borehole) GetYieldLitersPerHour() float64 {
	if x != nil {
		return x.YieldLitersPerHour
	}
	return 0
}

func (x *Borehole) GetIntervals() []*BoreholeInterval {
	if x != nil {
		return x.Intervals
	}
	return nil
}

func (x *Borehole) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Borehole) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

// This is like a license boundary and some polygons that will be made and sync
type ConcessionPolygon struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Code            string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"` // e.g "ML-2020-01 "
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"` // "kitui south"
	LicenseType     string                 `protobuf:"bytes,5,opt,name=license_type,json=licenseType,proto3" json:"license_type,omitempty"`
	GeojsonGeometry string                 `protobuf:"bytes,6,opt,name=geojson_geometry,json=geojsonGeometry,proto3" json:"geojson_geometry,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ValidUntil      int64                  `protobuf:"varint,8,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConcessionPolygon) Reset() {
	*x = ConcessionPolygon{}
	mi := &file_geoquerry_v1_geology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcessionPolygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcessionPolygon) ProtoMessage() {}

func (x *ConcessionPolygon) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_geology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcessionPolygon.ProtoReflect.Descriptor instead.
func (*ConcessionPolygon) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_geology_proto_rawDescGZIP(), []int{5}
}

func (x *ConcessionPolygon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConcessionPolygon) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ConcessionPolygon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConcessionPolygon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConcessionPolygon) GetLicenseType() string {
	if x != nil {
		return x.LicenseType
	}
	return ""
}

func (x *ConcessionPolygon) GetGeojsonGeometry() string {
	if x != nil {
		return x.GeojsonGeometry
	}
	return ""
}

func (x *ConcessionPolygon) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConcessionPolygon) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *ConcessionPolygon) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Vegetation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StationId     string                 `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PhotoR2Keys   []string               `protobuf:"bytes,4,rep,name=photo_r2_keys,json=photoR2Keys,proto3" json:"photo_r2_keys,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vegetation) Reset() {
	*x = Vegetation{}
	mi := &file_geoquerry_v1_geology_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vegetation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vegetation) ProtoMessage() {}

func (x *Vegetation) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_geology_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vegetation.ProtoReflect.Descriptor instead.
func (*Vegetation) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_geology_proto_rawDescGZIP(), []int{6}
}

func (x *Vegetation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vegetation) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *Vegetation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vegetation) GetPhotoR2Keys() []string {
	if x != nil {
		return x.PhotoR2Keys
	}
	return nil
}

func (x *Vegetation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Vegetation) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

var File_geoquerry_v1_geology_proto protoreflect.FileDescriptor

const file_geoquerry_v1_geology_proto_rawDesc = "" +
	"\n" +
	"\x1ageoquerry/v1/geology.proto\x12\fgeoquerry.v1\"\xe6\x02\n" +
	"\x15StructuralMeasurement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tR\tstationId\x12)\n" +
	"\x10measurement_type\x18\x03 \x01(\tR\x0fmeasurementType\x12\x16\n" +
	"\x06strike\x18\x04 \x01(\x01R\x06strike\x12\x10\n" +
	"\x03dip\x18\x05 \x01(\x01R\x03dip\x12#\n" +
	"\rdip_direction\x18\x06 \x01(\x01R\fdipDirection\x12\"\n" +
	"\fautocaptured\x18\a \x01(\bR\fautocaptured\x12\x14\n" +
	"\x05trend\x18\b \x01(\x01R\x05trend\x12\x16\n" +
	"\x06plunge\x18\t \x01(\x01R\x06plunge\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\f \x01(\bR\tisDeleted\"\xbd\x02\n" +
	"\n" +
	"RockSample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tR\tstationId\x12\x1d\n" +
	"\n" +
	"sample_tag\x18\x03 \x01(\tR\tsampleTag\x12'\n" +
	"\x0flithology_class\x18\x04 \x01(\tR\x0elithologyClass\x121\n" +
	"\x14mineralization_notes\x18\x05 \x01(\tR\x13mineralizationNotes\x12\"\n" +
	"\rphoto_r2_keys\x18\x06 \x03(\tR\vphotoR2Keys\x12#\n" +
	"\rassays_status\x18\a \x01(\tR\fassaysStatus\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\bR\tisDeleted\"\xaf\x04\n" +
	"\aStation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\televation\x18\a \x01(\x01R\televation\x12!\n" +
	"\fgps_accuracy\x18\b \x01(\x01R\vgpsAccuracy\x12)\n" +
	"\x10outcrop_exposure\x18\t \x01(\tR\x0foutcropExposure\x12\x1c\n" +
	"\tlithology\x18\n" +
	" \x01(\tR\tlithology\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\x12G\n" +
	"\fmeasurements\x18\f \x03(\v2#.geoquerry.v1.StructuralMeasurementR\fmeasurements\x122\n" +
	"\asamples\x18\r \x03(\v2\x18.geoquerry.v1.RockSampleR\asamples\x128\n" +
	"\n" +
	"vegetation\x18\x0e \x03(\v2\x18.geoquerry.v1.VegetationR\n" +
	"vegetation\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x10 \x01(\bR\tisDeleted\"\xee\x01\n" +
	"\x10BoreholeInterval\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vborehole_id\x18\x02 \x01(\tR\n" +
	"boreholeId\x12\x1d\n" +
	"\n" +
	"depth_from\x18\x03 \x01(\x01R\tdepthFrom\x12\x19\n" +
	"\bdepth_to\x18\x04 \x01(\x01R\adepthTo\x12\x1c\n" +
	"\tlithology\x18\x05 \x01(\tR\tlithology\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12/\n" +
	"\x13recovery_percentage\x18\a \x01(\x01R\x12recoveryPercentage\"\xe2\x03\n" +
	"\bBorehole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12#\n" +
	"\rborehole_code\x18\x03 \x01(\tR\fboreholeCode\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12)\n" +
	"\x10collar_elevation\x18\a \x01(\x01R\x0fcollarElevation\x12,\n" +
	"\x12total_depth_meters\x18\b \x01(\x01R\x10totalDepthMeters\x12,\n" +
	"\x12water_strike_depth\x18\t \x01(\x01R\x10waterStrikeDepth\x121\n" +
	"\x15yield_liters_per_hour\x18\n" +
	" \x01(\x01R\x12yieldLitersPerHour\x12<\n" +
	"\tintervals\x18\v \x03(\v2\x1e.geoquerry.v1.BoreholeIntervalR\tintervals\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\r \x01(\bR\tisDeleted\"\x90\x02\n" +
	"\x11ConcessionPolygon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\flicense_type\x18\x05 \x01(\tR\vlicenseType\x12)\n" +
	"\x10geojson_geometry\x18\x06 \x01(\tR\x0fgeojsonGeometry\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vvalid_until\x18\b \x01(\x03R\n" +
	"validUntil\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\xbf\x01\n" +
	"\n" +
	"Vegetation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tR\tstationId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\rphoto_r2_keys\x18\x04 \x03(\tR\vphotoR2Keys\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeletedB?Z=gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_geology_proto_rawDescOnce sync.Once
	file_geoquerry_v1_geology_proto_rawDescData []byte
)

func file_geoquerry_v1_geology_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_geology_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_geology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_geology_proto_rawDesc), len(file_geoquerry_v1_geology_proto_rawDesc)))
	})
	return file_geoquerry_v1_geology_proto_rawDescData
}

var file_geoquerry_v1_geology_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_geoquerry_v1_geology_proto_goTypes = []any{
	(*StructuralMeasurement)(nil), // 0: geoquerry.v1.StructuralMeasurement
	(*RockSample)(nil),            // 1: geoquerry.v1.RockSample
	(*Station)(nil),               // 2: geoquerry.v1.Station
	(*BoreholeInterval)(nil),      // 3: geoquerry.v1.BoreholeInterval
	(*Borehole)(nil),              // 4: geoquerry.v1.Borehole
	(*ConcessionPolygon)(nil),     // 5: geoquerry.v1.ConcessionPolygon
	(*Vegetation)(nil),            // 6: geoquerry.v1.Vegetation
}
var file_geoquerry_v1_geology_proto_depIdxs = []int32{
	0, // 0: geoquerry.v1.Station.measurements:type_name -> geoquerry.v1.StructuralMeasurement
	1, // 1: geoquerry.v1.Station.samples:type_name -> geoquerry.v1.RockSample
	6, // 2: geoquerry.v1.Station.vegetation:type_name -> geoquerry.v1.Vegetation
	3, // 3: geoquerry.v1.Borehole.intervals:type_name -> geoquerry.v1.BoreholeInterval
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_geology_proto_init() }
func file_geoquerry_v1_geology_proto_init() {
	if File_geoquerry_v1_geology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_geology_proto_rawDesc), len(file_geoquerry_v1_geology_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geoquerry_v1_geology_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_geology_proto_depIdxs,
		MessageInfos:      file_geoquerry_v1_geology_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_geology_proto = out.File
	file_geoquerry_v1_geology_proto_goTypes = nil
	file_geoquerry_v1_geology_proto_depIdxs = nil
}
