// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/gis.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatasetKind int32

const (
	DatasetKind_DATASET_KIND_UNSPECIFIED       DatasetKind = 0
	DatasetKind_DATASET_KIND_SHAPEFILE_ARCHIVE DatasetKind = 1
	DatasetKind_DATASET_KIND_GEOTIFF           DatasetKind = 2
	DatasetKind_DATASET_KIND_CWLS_LAS          DatasetKind = 3 // Borehole / well-log LAS
	DatasetKind_DATASET_KIND_ASPRS_LAS         DatasetKind = 4 // Airborne LiDAR point cloud
	DatasetKind_DATASET_KIND_SURVEY_CSV        DatasetKind = 5
)

// Enum value maps for DatasetKind.
var (
	DatasetKind_name = map[int32]string{
		0: "DATASET_KIND_UNSPECIFIED",
		1: "DATASET_KIND_SHAPEFILE_ARCHIVE",
		2: "DATASET_KIND_GEOTIFF",
		3: "DATASET_KIND_CWLS_LAS",
		4: "DATASET_KIND_ASPRS_LAS",
		5: "DATASET_KIND_SURVEY_CSV",
	}
	DatasetKind_value = map[string]int32{
		"DATASET_KIND_UNSPECIFIED":       0,
		"DATASET_KIND_SHAPEFILE_ARCHIVE": 1,
		"DATASET_KIND_GEOTIFF":           2,
		"DATASET_KIND_CWLS_LAS":          3,
		"DATASET_KIND_ASPRS_LAS":         4,
		"DATASET_KIND_SURVEY_CSV":        5,
	}
)

func (x DatasetKind) Enum() *DatasetKind {
	p := new(DatasetKind)
	*p = x
	return p
}

func (x DatasetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatasetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_geoquerry_v1_gis_proto_enumTypes[0].Descriptor()
}

func (DatasetKind) Type() protoreflect.EnumType {
	return &file_geoquerry_v1_gis_proto_enumTypes[0]
}

func (x DatasetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatasetKind.Descriptor instead.
func (DatasetKind) EnumDescriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{0}
}

type IngestionStatus int32

const (
	IngestionStatus_INGESTION_STATUS_UNSPECIFIED IngestionStatus = 0
	IngestionStatus_INGESTION_STATUS_QUARANTINED IngestionStatus = 1
	IngestionStatus_INGESTION_STATUS_SCANNING    IngestionStatus = 2
	IngestionStatus_INGESTION_STATUS_PROCESSING  IngestionStatus = 3
	IngestionStatus_INGESTION_STATUS_READY       IngestionStatus = 4
	IngestionStatus_INGESTION_STATUS_FAILED      IngestionStatus = 5
)

// Enum value maps for IngestionStatus.
var (
	IngestionStatus_name = map[int32]string{
		0: "INGESTION_STATUS_UNSPECIFIED",
		1: "INGESTION_STATUS_QUARANTINED",
		2: "INGESTION_STATUS_SCANNING",
		3: "INGESTION_STATUS_PROCESSING",
		4: "INGESTION_STATUS_READY",
		5: "INGESTION_STATUS_FAILED",
	}
	IngestionStatus_value = map[string]int32{
		"INGESTION_STATUS_UNSPECIFIED": 0,
		"INGESTION_STATUS_QUARANTINED": 1,
		"INGESTION_STATUS_SCANNING":    2,
		"INGESTION_STATUS_PROCESSING":  3,
		"INGESTION_STATUS_READY":       4,
		"INGESTION_STATUS_FAILED":      5,
	}
)

func (x IngestionStatus) Enum() *IngestionStatus {
	p := new(IngestionStatus)
	*p = x
	return p
}

func (x IngestionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_geoquerry_v1_gis_proto_enumTypes[1].Descriptor()
}

func (IngestionStatus) Type() protoreflect.EnumType {
	return &file_geoquerry_v1_gis_proto_enumTypes[1]
}

func (x IngestionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestionStatus.Descriptor instead.
func (IngestionStatus) EnumDescriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{1}
}

type CoordinateReferenceSystem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EpsgCode          string                 `protobuf:"bytes,1,opt,name=epsg_code,json=epsgCode,proto3" json:"epsg_code,omitempty"`                            // e.g. "EPSG:32636"
	DatumName         string                 `protobuf:"bytes,2,opt,name=datum_name,json=datumName,proto3" json:"datum_name,omitempty"`                         // e.g. "WGS 84" or "Arc 1960"
	ProjectionName    string                 `protobuf:"bytes,3,opt,name=projection_name,json=projectionName,proto3" json:"projection_name,omitempty"`          // e.g. "UTM Zone 36N"
	Units             string                 `protobuf:"bytes,4,opt,name=units,proto3" json:"units,omitempty"`                                                  // "metre", "degree", etc.
	TransformPipeline string                 `protobuf:"bytes,5,opt,name=transform_pipeline,json=transformPipeline,proto3" json:"transform_pipeline,omitempty"` // PROJ pipeline representation
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CoordinateReferenceSystem) Reset() {
	*x = CoordinateReferenceSystem{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateReferenceSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateReferenceSystem) ProtoMessage() {}

func (x *CoordinateReferenceSystem) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateReferenceSystem.ProtoReflect.Descriptor instead.
func (*CoordinateReferenceSystem) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinateReferenceSystem) GetEpsgCode() string {
	if x != nil {
		return x.EpsgCode
	}
	return ""
}

func (x *CoordinateReferenceSystem) GetDatumName() string {
	if x != nil {
		return x.DatumName
	}
	return ""
}

func (x *CoordinateReferenceSystem) GetProjectionName() string {
	if x != nil {
		return x.ProjectionName
	}
	return ""
}

func (x *CoordinateReferenceSystem) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *CoordinateReferenceSystem) GetTransformPipeline() string {
	if x != nil {
		return x.TransformPipeline
	}
	return ""
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinX          float64                `protobuf:"fixed64,1,opt,name=min_x,json=minX,proto3" json:"min_x,omitempty"`
	MinY          float64                `protobuf:"fixed64,2,opt,name=min_y,json=minY,proto3" json:"min_y,omitempty"`
	MaxX          float64                `protobuf:"fixed64,3,opt,name=max_x,json=maxX,proto3" json:"max_x,omitempty"`
	MaxY          float64                `protobuf:"fixed64,4,opt,name=max_y,json=maxY,proto3" json:"max_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{1}
}

func (x *BoundingBox) GetMinX() float64 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *BoundingBox) GetMinY() float64 {
	if x != nil {
		return x.MinY
	}
	return 0
}

func (x *BoundingBox) GetMaxX() float64 {
	if x != nil {
		return x.MaxX
	}
	return 0
}

func (x *BoundingBox) GetMaxY() float64 {
	if x != nil {
		return x.MaxY
	}
	return 0
}

type GisDatasetSummary struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	DatasetId      string                     `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	OrganizationId string                     `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                     `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Kind           DatasetKind                `protobuf:"varint,4,opt,name=kind,proto3,enum=geoquerry.v1.DatasetKind" json:"kind,omitempty"`
	DisplayName    string                     `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ByteSize       int64                      `protobuf:"varint,6,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Status         IngestionStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=geoquerry.v1.IngestionStatus" json:"status,omitempty"`
	FailureReason  string                     `protobuf:"bytes,8,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Crs            *CoordinateReferenceSystem `protobuf:"bytes,9,opt,name=crs,proto3" json:"crs,omitempty"`
	BoundsWgs84    *BoundingBox               `protobuf:"bytes,10,opt,name=bounds_wgs84,json=boundsWgs84,proto3" json:"bounds_wgs84,omitempty"`
	CreatedAt      int64                      `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                      `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GisDatasetSummary) Reset() {
	*x = GisDatasetSummary{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GisDatasetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GisDatasetSummary) ProtoMessage() {}

func (x *GisDatasetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GisDatasetSummary.ProtoReflect.Descriptor instead.
func (*GisDatasetSummary) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{2}
}

func (x *GisDatasetSummary) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *GisDatasetSummary) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GisDatasetSummary) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GisDatasetSummary) GetKind() DatasetKind {
	if x != nil {
		return x.Kind
	}
	return DatasetKind_DATASET_KIND_UNSPECIFIED
}

func (x *GisDatasetSummary) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GisDatasetSummary) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *GisDatasetSummary) GetStatus() IngestionStatus {
	if x != nil {
		return x.Status
	}
	return IngestionStatus_INGESTION_STATUS_UNSPECIFIED
}

func (x *GisDatasetSummary) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *GisDatasetSummary) GetCrs() *CoordinateReferenceSystem {
	if x != nil {
		return x.Crs
	}
	return nil
}

func (x *GisDatasetSummary) GetBoundsWgs84() *BoundingBox {
	if x != nil {
		return x.BoundsWgs84
	}
	return nil
}

func (x *GisDatasetSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GisDatasetSummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type InitiateDatasetUploadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Kind           DatasetKind            `protobuf:"varint,3,opt,name=kind,proto3,enum=geoquerry.v1.DatasetKind" json:"kind,omitempty"`
	DisplayName    string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ByteSize       int64                  `protobuf:"varint,5,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	ContentType    string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateDatasetUploadRequest) Reset() {
	*x = InitiateDatasetUploadRequest{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateDatasetUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateDatasetUploadRequest) ProtoMessage() {}

func (x *InitiateDatasetUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateDatasetUploadRequest.ProtoReflect.Descriptor instead.
func (*InitiateDatasetUploadRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{3}
}

func (x *InitiateDatasetUploadRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *InitiateDatasetUploadRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *InitiateDatasetUploadRequest) GetKind() DatasetKind {
	if x != nil {
		return x.Kind
	}
	return DatasetKind_DATASET_KIND_UNSPECIFIED
}

func (x *InitiateDatasetUploadRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *InitiateDatasetUploadRequest) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *InitiateDatasetUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type InitiateDatasetUploadResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UploadId           string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PresignedUploadUrl string                 `protobuf:"bytes,2,opt,name=presigned_upload_url,json=presignedUploadUrl,proto3" json:"presigned_upload_url,omitempty"`
	ExpiresAt          int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RequiredHeaders    map[string]string      `protobuf:"bytes,4,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitiateDatasetUploadResponse) Reset() {
	*x = InitiateDatasetUploadResponse{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateDatasetUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateDatasetUploadResponse) ProtoMessage() {}

func (x *InitiateDatasetUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateDatasetUploadResponse.ProtoReflect.Descriptor instead.
func (*InitiateDatasetUploadResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{4}
}

func (x *InitiateDatasetUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *InitiateDatasetUploadResponse) GetPresignedUploadUrl() string {
	if x != nil {
		return x.PresignedUploadUrl
	}
	return ""
}

func (x *InitiateDatasetUploadResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *InitiateDatasetUploadResponse) GetRequiredHeaders() map[string]string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

type CompleteDatasetUploadRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId         string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId              string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UploadId               string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ExpectedChecksumSha256 string                 `protobuf:"bytes,4,opt,name=expected_checksum_sha256,json=expectedChecksumSha256,proto3" json:"expected_checksum_sha256,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CompleteDatasetUploadRequest) Reset() {
	*x = CompleteDatasetUploadRequest{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteDatasetUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteDatasetUploadRequest) ProtoMessage() {}

func (x *CompleteDatasetUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteDatasetUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteDatasetUploadRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteDatasetUploadRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CompleteDatasetUploadRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CompleteDatasetUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteDatasetUploadRequest) GetExpectedChecksumSha256() string {
	if x != nil {
		return x.ExpectedChecksumSha256
	}
	return ""
}

type CompleteDatasetUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Status        IngestionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=geoquerry.v1.IngestionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteDatasetUploadResponse) Reset() {
	*x = CompleteDatasetUploadResponse{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteDatasetUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteDatasetUploadResponse) ProtoMessage() {}

func (x *CompleteDatasetUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteDatasetUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteDatasetUploadResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteDatasetUploadResponse) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *CompleteDatasetUploadResponse) GetStatus() IngestionStatus {
	if x != nil {
		return x.Status
	}
	return IngestionStatus_INGESTION_STATUS_UNSPECIFIED
}

type GetDatasetStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DatasetId      string                 `protobuf:"bytes,3,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDatasetStatusRequest) Reset() {
	*x = GetDatasetStatusRequest{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetStatusRequest) ProtoMessage() {}

func (x *GetDatasetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDatasetStatusRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{7}
}

func (x *GetDatasetStatusRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetDatasetStatusRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetDatasetStatusRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type GetDatasetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       *GisDatasetSummary     `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasetStatusResponse) Reset() {
	*x = GetDatasetStatusResponse{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetStatusResponse) ProtoMessage() {}

func (x *GetDatasetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDatasetStatusResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{8}
}

func (x *GetDatasetStatusResponse) GetDataset() *GisDatasetSummary {
	if x != nil {
		return x.Dataset
	}
	return nil
}

type ListDatasetsRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	OrganizationId string                   `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Pagination     *CursorPaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{9}
}

func (x *ListDatasetsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListDatasetsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListDatasetsRequest) GetPagination() *CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Datasets      []*GisDatasetSummary      `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	Pagination    *CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_geoquerry_v1_gis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_gis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_gis_proto_rawDescGZIP(), []int{10}
}

func (x *ListDatasetsResponse) GetDatasets() []*GisDatasetSummary {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *ListDatasetsResponse) GetPagination() *CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_geoquerry_v1_gis_proto protoreflect.FileDescriptor

const file_geoquerry_v1_gis_proto_rawDesc = "" +
	"\n" +
	"\x16geoquerry/v1/gis.proto\x12\fgeoquerry.v1\x1a\x19geoquerry/v1/common.proto\"\xc5\x01\n" +
	"\x19CoordinateReferenceSystem\x12\x1b\n" +
	"\tepsg_code\x18\x01 \x01(\tR\bepsgCode\x12\x1d\n" +
	"\n" +
	"datum_name\x18\x02 \x01(\tR\tdatumName\x12'\n" +
	"\x0fprojection_name\x18\x03 \x01(\tR\x0eprojectionName\x12\x14\n" +
	"\x05units\x18\x04 \x01(\tR\x05units\x12-\n" +
	"\x12transform_pipeline\x18\x05 \x01(\tR\x11transformPipeline\"a\n" +
	"\vBoundingBox\x12\x13\n" +
	"\x05min_x\x18\x01 \x01(\x01R\x04minX\x12\x13\n" +
	"\x05min_y\x18\x02 \x01(\x01R\x04minY\x12\x13\n" +
	"\x05max_x\x18\x03 \x01(\x01R\x04maxX\x12\x13\n" +
	"\x05max_y\x18\x04 \x01(\x01R\x04maxY\"\xfe\x03\n" +
	"\x11GisDatasetSummary\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12-\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x19.geoquerry.v1.DatasetKindR\x04kind\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tbyte_size\x18\x06 \x01(\x03R\bbyteSize\x125\n" +
	"\x06status\x18\a \x01(\x0e2\x1d.geoquerry.v1.IngestionStatusR\x06status\x12%\n" +
	"\x0efailure_reason\x18\b \x01(\tR\rfailureReason\x129\n" +
	"\x03crs\x18\t \x01(\v2'.geoquerry.v1.CoordinateReferenceSystemR\x03crs\x12<\n" +
	"\fbounds_wgs84\x18\n" +
	" \x01(\v2\x19.geoquerry.v1.BoundingBoxR\vboundsWgs84\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"\xf8\x01\n" +
	"\x1cInitiateDatasetUploadRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12-\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x19.geoquerry.v1.DatasetKindR\x04kind\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tbyte_size\x18\x05 \x01(\x03R\bbyteSize\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\"\xbe\x02\n" +
	"\x1dInitiateDatasetUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x120\n" +
	"\x14presigned_upload_url\x18\x02 \x01(\tR\x12presignedUploadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12k\n" +
	"\x10required_headers\x18\x04 \x03(\v2@.geoquerry.v1.InitiateDatasetUploadResponse.RequiredHeadersEntryR\x0frequiredHeaders\x1aB\n" +
	"\x14RequiredHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\x1cCompleteDatasetUploadRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x128\n" +
	"\x18expected_checksum_sha256\x18\x04 \x01(\tR\x16expectedChecksumSha256\"u\n" +
	"\x1dCompleteDatasetUploadResponse\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.geoquerry.v1.IngestionStatusR\x06status\"\x80\x01\n" +
	"\x17GetDatasetStatusRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x03 \x01(\tR\tdatasetId\"U\n" +
	"\x18GetDatasetStatusResponse\x129\n" +
	"\adataset\x18\x01 \x01(\v2\x1f.geoquerry.v1.GisDatasetSummaryR\adataset\"\xa4\x01\n" +
	"\x13ListDatasetsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12E\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2%.geoquerry.v1.CursorPaginationRequestR\n" +
	"pagination\"\x9b\x01\n" +
	"\x14ListDatasetsResponse\x12;\n" +
	"\bdatasets\x18\x01 \x03(\v2\x1f.geoquerry.v1.GisDatasetSummaryR\bdatasets\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.geoquerry.v1.CursorPaginationResponseR\n" +
	"pagination*\xbd\x01\n" +
	"\vDatasetKind\x12\x1c\n" +
	"\x18DATASET_KIND_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDATASET_KIND_SHAPEFILE_ARCHIVE\x10\x01\x12\x18\n" +
	"\x14DATASET_KIND_GEOTIFF\x10\x02\x12\x19\n" +
	"\x15DATASET_KIND_CWLS_LAS\x10\x03\x12\x1a\n" +
	"\x16DATASET_KIND_ASPRS_LAS\x10\x04\x12\x1b\n" +
	"\x17DATASET_KIND_SURVEY_CSV\x10\x05*\xce\x01\n" +
	"\x0fIngestionStatus\x12 \n" +
	"\x1cINGESTION_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cINGESTION_STATUS_QUARANTINED\x10\x01\x12\x1d\n" +
	"\x19INGESTION_STATUS_SCANNING\x10\x02\x12\x1f\n" +
	"\x1bINGESTION_STATUS_PROCESSING\x10\x03\x12\x1a\n" +
	"\x16INGESTION_STATUS_READY\x10\x04\x12\x1b\n" +
	"\x17INGESTION_STATUS_FAILED\x10\x052\xb3\x03\n" +
	"\x13GisIngestionService\x12p\n" +
	"\x15InitiateDatasetUpload\x12*.geoquerry.v1.InitiateDatasetUploadRequest\x1a+.geoquerry.v1.InitiateDatasetUploadResponse\x12p\n" +
	"\x15CompleteDatasetUpload\x12*.geoquerry.v1.CompleteDatasetUploadRequest\x1a+.geoquerry.v1.CompleteDatasetUploadResponse\x12a\n" +
	"\x10GetDatasetStatus\x12%.geoquerry.v1.GetDatasetStatusRequest\x1a&.geoquerry.v1.GetDatasetStatusResponse\x12U\n" +
	"\fListDatasets\x12!.geoquerry.v1.ListDatasetsRequest\x1a\".geoquerry.v1.ListDatasetsResponseBLZJgitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1;geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_gis_proto_rawDescOnce sync.Once
	file_geoquerry_v1_gis_proto_rawDescData []byte
)

func file_geoquerry_v1_gis_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_gis_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_gis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_gis_proto_rawDesc), len(file_geoquerry_v1_gis_proto_rawDesc)))
	})
	return file_geoquerry_v1_gis_proto_rawDescData
}

var file_geoquerry_v1_gis_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_geoquerry_v1_gis_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_geoquerry_v1_gis_proto_goTypes = []any{
	(DatasetKind)(0),                      // 0: geoquerry.v1.DatasetKind
	(IngestionStatus)(0),                  // 1: geoquerry.v1.IngestionStatus
	(*CoordinateReferenceSystem)(nil),     // 2: geoquerry.v1.CoordinateReferenceSystem
	(*BoundingBox)(nil),                   // 3: geoquerry.v1.BoundingBox
	(*GisDatasetSummary)(nil),             // 4: geoquerry.v1.GisDatasetSummary
	(*InitiateDatasetUploadRequest)(nil),  // 5: geoquerry.v1.InitiateDatasetUploadRequest
	(*InitiateDatasetUploadResponse)(nil), // 6: geoquerry.v1.InitiateDatasetUploadResponse
	(*CompleteDatasetUploadRequest)(nil),  // 7: geoquerry.v1.CompleteDatasetUploadRequest
	(*CompleteDatasetUploadResponse)(nil), // 8: geoquerry.v1.CompleteDatasetUploadResponse
	(*GetDatasetStatusRequest)(nil),       // 9: geoquerry.v1.GetDatasetStatusRequest
	(*GetDatasetStatusResponse)(nil),      // 10: geoquerry.v1.GetDatasetStatusResponse
	(*ListDatasetsRequest)(nil),           // 11: geoquerry.v1.ListDatasetsRequest
	(*ListDatasetsResponse)(nil),          // 12: geoquerry.v1.ListDatasetsResponse
	nil,                                   // 13: geoquerry.v1.InitiateDatasetUploadResponse.RequiredHeadersEntry
	(*CursorPaginationRequest)(nil),       // 14: geoquerry.v1.CursorPaginationRequest
	(*CursorPaginationResponse)(nil),      // 15: geoquerry.v1.CursorPaginationResponse
}
var file_geoquerry_v1_gis_proto_depIdxs = []int32{
	0,  // 0: geoquerry.v1.GisDatasetSummary.kind:type_name -> geoquerry.v1.DatasetKind
	1,  // 1: geoquerry.v1.GisDatasetSummary.status:type_name -> geoquerry.v1.IngestionStatus
	2,  // 2: geoquerry.v1.GisDatasetSummary.crs:type_name -> geoquerry.v1.CoordinateReferenceSystem
	3,  // 3: geoquerry.v1.GisDatasetSummary.bounds_wgs84:type_name -> geoquerry.v1.BoundingBox
	0,  // 4: geoquerry.v1.InitiateDatasetUploadRequest.kind:type_name -> geoquerry.v1.DatasetKind
	13, // 5: geoquerry.v1.InitiateDatasetUploadResponse.required_headers:type_name -> geoquerry.v1.InitiateDatasetUploadResponse.RequiredHeadersEntry
	1,  // 6: geoquerry.v1.CompleteDatasetUploadResponse.status:type_name -> geoquerry.v1.IngestionStatus
	4,  // 7: geoquerry.v1.GetDatasetStatusResponse.dataset:type_name -> geoquerry.v1.GisDatasetSummary
	14, // 8: geoquerry.v1.ListDatasetsRequest.pagination:type_name -> geoquerry.v1.CursorPaginationRequest
	4,  // 9: geoquerry.v1.ListDatasetsResponse.datasets:type_name -> geoquerry.v1.GisDatasetSummary
	15, // 10: geoquerry.v1.ListDatasetsResponse.pagination:type_name -> geoquerry.v1.CursorPaginationResponse
	5,  // 11: geoquerry.v1.GisIngestionService.InitiateDatasetUpload:input_type -> geoquerry.v1.InitiateDatasetUploadRequest
	7,  // 12: geoquerry.v1.GisIngestionService.CompleteDatasetUpload:input_type -> geoquerry.v1.CompleteDatasetUploadRequest
	9,  // 13: geoquerry.v1.GisIngestionService.GetDatasetStatus:input_type -> geoquerry.v1.GetDatasetStatusRequest
	11, // 14: geoquerry.v1.GisIngestionService.ListDatasets:input_type -> geoquerry.v1.ListDatasetsRequest
	6,  // 15: geoquerry.v1.GisIngestionService.InitiateDatasetUpload:output_type -> geoquerry.v1.InitiateDatasetUploadResponse
	8,  // 16: geoquerry.v1.GisIngestionService.CompleteDatasetUpload:output_type -> geoquerry.v1.CompleteDatasetUploadResponse
	10, // 17: geoquerry.v1.GisIngestionService.GetDatasetStatus:output_type -> geoquerry.v1.GetDatasetStatusResponse
	12, // 18: geoquerry.v1.GisIngestionService.ListDatasets:output_type -> geoquerry.v1.ListDatasetsResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_gis_proto_init() }
func file_geoquerry_v1_gis_proto_init() {
	if File_geoquerry_v1_gis_proto != nil {
		return
	}
	file_geoquerry_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_gis_proto_rawDesc), len(file_geoquerry_v1_gis_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geoquerry_v1_gis_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_gis_proto_depIdxs,
		EnumInfos:         file_geoquerry_v1_gis_proto_enumTypes,
		MessageInfos:      file_geoquerry_v1_gis_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_gis_proto = out.File
	file_geoquerry_v1_gis_proto_goTypes = nil
	file_geoquerry_v1_gis_proto_depIdxs = nil
}
