// media.proto — photo upload contract for Cloudflare R2.
//
// WHY PRESIGNED URLS (device -> R2 direct)?
// Field photos are multi-megabyte; routing them through the Go API (on a
// 512 MB Koyeb Nano) would burn memory, bandwidth and time. Instead the
// client asks the API for a short-lived presigned PUT URL and uploads
// DIRECTLY to Cloudflare R2 — zero egress fees, nothing binary ever
// touches the API server. The DB only ever stores the object key.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/media.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePhotoUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project and (optional) station scope the photo to, used to build a
	// tidy object key: photos/{project}/{station|unfiled}/{uuid}.{ext}
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	StationId string `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // optional: photos may be taken before a station exists
	// Original file name — used ONLY to infer a safe extension (.jpg etc).
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Client-declared MIME type; the server enforces an image allowlist so a
	// presigned URL can never be used to plant arbitrary content.
	ContentType string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Client-declared size; the server caps it so the URL can't be used for
	// arbitrarily large uploads.
	ContentLengthBytes int64 `protobuf:"varint,5,opt,name=content_length_bytes,json=contentLengthBytes,proto3" json:"content_length_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreatePhotoUploadRequest) Reset() {
	*x = CreatePhotoUploadRequest{}
	mi := &file_geoquerry_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePhotoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhotoUploadRequest) ProtoMessage() {}

func (x *CreatePhotoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhotoUploadRequest.ProtoReflect.Descriptor instead.
func (*CreatePhotoUploadRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePhotoUploadRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreatePhotoUploadRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *CreatePhotoUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreatePhotoUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreatePhotoUploadRequest) GetContentLengthBytes() int64 {
	if x != nil {
		return x.ContentLengthBytes
	}
	return 0
}

type CreatePhotoUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PUT this URL directly to R2 with the SAME Content-Type header within
	// the expiry window. No other headers are required (signature covers
	// them), which is what makes it work from any HTTP client.
	UploadUrl string `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	// The object key. After a successful upload, the client stores THIS
	// string in RockSample.photo_r2_keys / Vegetation.photo_r2_keys and it
	// syncs like any other field edit.
	R2Key string `protobuf:"bytes,2,opt,name=r2_key,json=r2Key,proto3" json:"r2_key,omitempty"`
	// Unix ms after which the URL stops working (default 5 minutes).
	ExpiresAt     int64 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePhotoUploadResponse) Reset() {
	*x = CreatePhotoUploadResponse{}
	mi := &file_geoquerry_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePhotoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhotoUploadResponse) ProtoMessage() {}

func (x *CreatePhotoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhotoUploadResponse.ProtoReflect.Descriptor instead.
func (*CreatePhotoUploadResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePhotoUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreatePhotoUploadResponse) GetR2Key() string {
	if x != nil {
		return x.R2Key
	}
	return ""
}

func (x *CreatePhotoUploadResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_geoquerry_v1_media_proto protoreflect.FileDescriptor

const file_geoquerry_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x18geoquerry/v1/media.proto\x12\fgeoquerry.v1\"\xca\x01\n" +
	"\x18CreatePhotoUploadRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tR\tstationId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x120\n" +
	"\x14content_length_bytes\x18\x05 \x01(\x03R\x12contentLengthBytes\"p\n" +
	"\x19CreatePhotoUploadResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x15\n" +
	"\x06r2_key\x18\x02 \x01(\tR\x05r2Key\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAtBLZJgitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1;geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_media_proto_rawDescOnce sync.Once
	file_geoquerry_v1_media_proto_rawDescData []byte
)

func file_geoquerry_v1_media_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_media_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_media_proto_rawDesc), len(file_geoquerry_v1_media_proto_rawDesc)))
	})
	return file_geoquerry_v1_media_proto_rawDescData
}

var file_geoquerry_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_geoquerry_v1_media_proto_goTypes = []any{
	(*CreatePhotoUploadRequest)(nil),  // 0: geoquerry.v1.CreatePhotoUploadRequest
	(*CreatePhotoUploadResponse)(nil), // 1: geoquerry.v1.CreatePhotoUploadResponse
}
var file_geoquerry_v1_media_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_media_proto_init() }
func file_geoquerry_v1_media_proto_init() {
	if File_geoquerry_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_media_proto_rawDesc), len(file_geoquerry_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geoquerry_v1_media_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_media_proto_depIdxs,
		MessageInfos:      file_geoquerry_v1_media_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_media_proto = out.File
	file_geoquerry_v1_media_proto_goTypes = nil
	file_geoquerry_v1_media_proto_depIdxs = nil
}
