// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/sync.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStatus int32

const (
	SyncStatus_SYNC_STATUS_UNSPECIFIED        SyncStatus = 0
	SyncStatus_SYNC_STATUS_SYNCED             SyncStatus = 1
	SyncStatus_SYNC_STATUS_CONFLICT_OVERWROTE SyncStatus = 2
	SyncStatus_SYNC_STATUS_CONFLICT_STALE     SyncStatus = 3
	SyncStatus_SYNC_STATUS_REJECTED           SyncStatus = 4
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_UNSPECIFIED",
		1: "SYNC_STATUS_SYNCED",
		2: "SYNC_STATUS_CONFLICT_OVERWROTE",
		3: "SYNC_STATUS_CONFLICT_STALE",
		4: "SYNC_STATUS_REJECTED",
	}
	SyncStatus_value = map[string]int32{
		"SYNC_STATUS_UNSPECIFIED":        0,
		"SYNC_STATUS_SYNCED":             1,
		"SYNC_STATUS_CONFLICT_OVERWROTE": 2,
		"SYNC_STATUS_CONFLICT_STALE":     3,
		"SYNC_STATUS_REJECTED":           4,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_geoquerry_v1_sync_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_geoquerry_v1_sync_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_geoquerry_v1_sync_proto_rawDescGZIP(), []int{0}
}

type PushSyncQueueRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ProjectId       string                   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientDeviceId  string                   `protobuf:"bytes,2,opt,name=client_device_id,json=clientDeviceId,proto3" json:"client_device_id,omitempty"`
	Stations        []*Station               `protobuf:"bytes,3,rep,name=stations,proto3" json:"stations,omitempty"`
	Measurements    []*StructuralMeasurement `protobuf:"bytes,4,rep,name=measurements,proto3" json:"measurements,omitempty"`
	Samples         []*RockSample            `protobuf:"bytes,5,rep,name=samples,proto3" json:"samples,omitempty"`
	Boreholes       []*Borehole              `protobuf:"bytes,6,rep,name=boreholes,proto3" json:"boreholes,omitempty"`
	Vegetation      []*Vegetation            `protobuf:"bytes,7,rep,name=vegetation,proto3" json:"vegetation,omitempty"`
	ClientTimestamp int64                    `protobuf:"varint,8,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushSyncQueueRequest) Reset() {
	*x = PushSyncQueueRequest{}
	mi := &file_geoquerry_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSyncQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSyncQueueRequest) ProtoMessage() {}

func (x *PushSyncQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSyncQueueRequest.ProtoReflect.Descriptor instead.
func (*PushSyncQueueRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *PushSyncQueueRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PushSyncQueueRequest) GetClientDeviceId() string {
	if x != nil {
		return x.ClientDeviceId
	}
	return ""
}

func (x *PushSyncQueueRequest) GetStations() []*Station {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *PushSyncQueueRequest) GetMeasurements() []*StructuralMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *PushSyncQueueRequest) GetSamples() []*RockSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *PushSyncQueueRequest) GetBoreholes() []*Borehole {
	if x != nil {
		return x.Boreholes
	}
	return nil
}

func (x *PushSyncQueueRequest) GetVegetation() []*Vegetation {
	if x != nil {
		return x.Vegetation
	}
	return nil
}

func (x *PushSyncQueueRequest) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

type EntitySyncResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        SyncStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=geoquerry.v1.SyncStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySyncResult) Reset() {
	*x = EntitySyncResult{}
	mi := &file_geoquerry_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySyncResult) ProtoMessage() {}

func (x *EntitySyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySyncResult.ProtoReflect.Descriptor instead.
func (*EntitySyncResult) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *EntitySyncResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntitySyncResult) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *EntitySyncResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PushSyncQueueResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTimestamp     int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	StationResults      []*EntitySyncResult    `protobuf:"bytes,3,rep,name=station_results,json=stationResults,proto3" json:"station_results,omitempty"`
	MeasurementsResults []*EntitySyncResult    `protobuf:"bytes,4,rep,name=measurements_results,json=measurementsResults,proto3" json:"measurements_results,omitempty"`
	SamplesResults      []*EntitySyncResult    `protobuf:"bytes,5,rep,name=samples_results,json=samplesResults,proto3" json:"samples_results,omitempty"`
	VegetationResults   []*EntitySyncResult    `protobuf:"bytes,6,rep,name=vegetation_results,json=vegetationResults,proto3" json:"vegetation_results,omitempty"`
	BoreholesResults    []*EntitySyncResult    `protobuf:"bytes,7,rep,name=boreholes_results,json=boreholesResults,proto3" json:"boreholes_results,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PushSyncQueueResponse) Reset() {
	*x = PushSyncQueueResponse{}
	mi := &file_geoquerry_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSyncQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSyncQueueResponse) ProtoMessage() {}

func (x *PushSyncQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSyncQueueResponse.ProtoReflect.Descriptor instead.
func (*PushSyncQueueResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *PushSyncQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushSyncQueueResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *PushSyncQueueResponse) GetStationResults() []*EntitySyncResult {
	if x != nil {
		return x.StationResults
	}
	return nil
}

func (x *PushSyncQueueResponse) GetMeasurementsResults() []*EntitySyncResult {
	if x != nil {
		return x.MeasurementsResults
	}
	return nil
}

func (x *PushSyncQueueResponse) GetSamplesResults() []*EntitySyncResult {
	if x != nil {
		return x.SamplesResults
	}
	return nil
}

func (x *PushSyncQueueResponse) GetVegetationResults() []*EntitySyncResult {
	if x != nil {
		return x.VegetationResults
	}
	return nil
}

func (x *PushSyncQueueResponse) GetBoreholesResults() []*EntitySyncResult {
	if x != nil {
		return x.BoreholesResults
	}
	return nil
}

type PullProjectDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SinceTimestamp int64                  `protobuf:"varint,2,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"` // when last was the sync done
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PullProjectDataRequest) Reset() {
	*x = PullProjectDataRequest{}
	mi := &file_geoquerry_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullProjectDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullProjectDataRequest) ProtoMessage() {}

func (x *PullProjectDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullProjectDataRequest.ProtoReflect.Descriptor instead.
func (*PullProjectDataRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *PullProjectDataRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PullProjectDataRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

type PullProjectDataResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ServerTimestamp int64                    `protobuf:"varint,1,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	Stations        []*Station               `protobuf:"bytes,2,rep,name=stations,proto3" json:"stations,omitempty"`
	Measurements    []*StructuralMeasurement `protobuf:"bytes,3,rep,name=measurements,proto3" json:"measurements,omitempty"`
	Samples         []*RockSample            `protobuf:"bytes,4,rep,name=samples,proto3" json:"samples,omitempty"`
	Boreholes       []*Borehole              `protobuf:"bytes,5,rep,name=boreholes,proto3" json:"boreholes,omitempty"`
	Vegetation      []*Vegetation            `protobuf:"bytes,6,rep,name=vegetation,proto3" json:"vegetation,omitempty"`
	Concessions     []*ConcessionPolygon     `protobuf:"bytes,7,rep,name=concessions,proto3" json:"concessions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PullProjectDataResponse) Reset() {
	*x = PullProjectDataResponse{}
	mi := &file_geoquerry_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullProjectDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullProjectDataResponse) ProtoMessage() {}

func (x *PullProjectDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullProjectDataResponse.ProtoReflect.Descriptor instead.
func (*PullProjectDataResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *PullProjectDataResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *PullProjectDataResponse) GetStations() []*Station {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *PullProjectDataResponse) GetMeasurements() []*StructuralMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *PullProjectDataResponse) GetSamples() []*RockSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *PullProjectDataResponse) GetBoreholes() []*Borehole {
	if x != nil {
		return x.Boreholes
	}
	return nil
}

func (x *PullProjectDataResponse) GetVegetation() []*Vegetation {
	if x != nil {
		return x.Vegetation
	}
	return nil
}

func (x *PullProjectDataResponse) GetConcessions() []*ConcessionPolygon {
	if x != nil {
		return x.Concessions
	}
	return nil
}

var File_geoquerry_v1_sync_proto protoreflect.FileDescriptor

const file_geoquerry_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x17geoquerry/v1/sync.proto\x12\fgeoquerry.v1\x1a\x1ageoquerry/v1/geology.proto\"\xaa\x03\n" +
	"\x14PushSyncQueueRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12(\n" +
	"\x10client_device_id\x18\x02 \x01(\tR\x0eclientDeviceId\x121\n" +
	"\bstations\x18\x03 \x03(\v2\x15.geoquerry.v1.StationR\bstations\x12G\n" +
	"\fmeasurements\x18\x04 \x03(\v2#.geoquerry.v1.StructuralMeasurementR\fmeasurements\x122\n" +
	"\asamples\x18\x05 \x03(\v2\x18.geoquerry.v1.RockSampleR\asamples\x124\n" +
	"\tboreholes\x18\x06 \x03(\v2\x16.geoquerry.v1.BoreholeR\tboreholes\x128\n" +
	"\n" +
	"vegetation\x18\a \x03(\v2\x18.geoquerry.v1.VegetationR\n" +
	"vegetation\x12)\n" +
	"\x10client_timestamp\x18\b \x01(\x03R\x0fclientTimestamp\"y\n" +
	"\x10EntitySyncResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.geoquerry.v1.SyncStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xdd\x03\n" +
	"\x15PushSyncQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\x12G\n" +
	"\x0fstation_results\x18\x03 \x03(\v2\x1e.geoquerry.v1.EntitySyncResultR\x0estationResults\x12Q\n" +
	"\x14measurements_results\x18\x04 \x03(\v2\x1e.geoquerry.v1.EntitySyncResultR\x13measurementsResults\x12G\n" +
	"\x0fsamples_results\x18\x05 \x03(\v2\x1e.geoquerry.v1.EntitySyncResultR\x0esamplesResults\x12M\n" +
	"\x12vegetation_results\x18\x06 \x03(\v2\x1e.geoquerry.v1.EntitySyncResultR\x11vegetationResults\x12K\n" +
	"\x11boreholes_results\x18\a \x03(\v2\x1e.geoquerry.v1.EntitySyncResultR\x10boreholesResults\"`\n" +
	"\x16PullProjectDataRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12'\n" +
	"\x0fsince_timestamp\x18\x02 \x01(\x03R\x0esinceTimestamp\"\xa7\x03\n" +
	"\x17PullProjectDataResponse\x12)\n" +
	"\x10server_timestamp\x18\x01 \x01(\x03R\x0fserverTimestamp\x121\n" +
	"\bstations\x18\x02 \x03(\v2\x15.geoquerry.v1.StationR\bstations\x12G\n" +
	"\fmeasurements\x18\x03 \x03(\v2#.geoquerry.v1.StructuralMeasurementR\fmeasurements\x122\n" +
	"\asamples\x18\x04 \x03(\v2\x18.geoquerry.v1.RockSampleR\asamples\x124\n" +
	"\tboreholes\x18\x05 \x03(\v2\x16.geoquerry.v1.BoreholeR\tboreholes\x128\n" +
	"\n" +
	"vegetation\x18\x06 \x03(\v2\x18.geoquerry.v1.VegetationR\n" +
	"vegetation\x12A\n" +
	"\vconcessions\x18\a \x03(\v2\x1f.geoquerry.v1.ConcessionPolygonR\vconcessions*\x9f\x01\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\x17SYNC_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SYNC_STATUS_SYNCED\x10\x01\x12\"\n" +
	"\x1eSYNC_STATUS_CONFLICT_OVERWROTE\x10\x02\x12\x1e\n" +
	"\x1aSYNC_STATUS_CONFLICT_STALE\x10\x03\x12\x18\n" +
	"\x14SYNC_STATUS_REJECTED\x10\x04BLZJgitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1;geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_sync_proto_rawDescOnce sync.Once
	file_geoquerry_v1_sync_proto_rawDescData []byte
)

func file_geoquerry_v1_sync_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_sync_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_sync_proto_rawDesc), len(file_geoquerry_v1_sync_proto_rawDesc)))
	})
	return file_geoquerry_v1_sync_proto_rawDescData
}

var file_geoquerry_v1_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_geoquerry_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_geoquerry_v1_sync_proto_goTypes = []any{
	(SyncStatus)(0),                 // 0: geoquerry.v1.SyncStatus
	(*PushSyncQueueRequest)(nil),    // 1: geoquerry.v1.PushSyncQueueRequest
	(*EntitySyncResult)(nil),        // 2: geoquerry.v1.EntitySyncResult
	(*PushSyncQueueResponse)(nil),   // 3: geoquerry.v1.PushSyncQueueResponse
	(*PullProjectDataRequest)(nil),  // 4: geoquerry.v1.PullProjectDataRequest
	(*PullProjectDataResponse)(nil), // 5: geoquerry.v1.PullProjectDataResponse
	(*Station)(nil),                 // 6: geoquerry.v1.Station
	(*StructuralMeasurement)(nil),   // 7: geoquerry.v1.StructuralMeasurement
	(*RockSample)(nil),              // 8: geoquerry.v1.RockSample
	(*Borehole)(nil),                // 9: geoquerry.v1.Borehole
	(*Vegetation)(nil),              // 10: geoquerry.v1.Vegetation
	(*ConcessionPolygon)(nil),       // 11: geoquerry.v1.ConcessionPolygon
}
var file_geoquerry_v1_sync_proto_depIdxs = []int32{
	6,  // 0: geoquerry.v1.PushSyncQueueRequest.stations:type_name -> geoquerry.v1.Station
	7,  // 1: geoquerry.v1.PushSyncQueueRequest.measurements:type_name -> geoquerry.v1.StructuralMeasurement
	8,  // 2: geoquerry.v1.PushSyncQueueRequest.samples:type_name -> geoquerry.v1.RockSample
	9,  // 3: geoquerry.v1.PushSyncQueueRequest.boreholes:type_name -> geoquerry.v1.Borehole
	10, // 4: geoquerry.v1.PushSyncQueueRequest.vegetation:type_name -> geoquerry.v1.Vegetation
	0,  // 5: geoquerry.v1.EntitySyncResult.status:type_name -> geoquerry.v1.SyncStatus
	2,  // 6: geoquerry.v1.PushSyncQueueResponse.station_results:type_name -> geoquerry.v1.EntitySyncResult
	2,  // 7: geoquerry.v1.PushSyncQueueResponse.measurements_results:type_name -> geoquerry.v1.EntitySyncResult
	2,  // 8: geoquerry.v1.PushSyncQueueResponse.samples_results:type_name -> geoquerry.v1.EntitySyncResult
	2,  // 9: geoquerry.v1.PushSyncQueueResponse.vegetation_results:type_name -> geoquerry.v1.EntitySyncResult
	2,  // 10: geoquerry.v1.PushSyncQueueResponse.boreholes_results:type_name -> geoquerry.v1.EntitySyncResult
	6,  // 11: geoquerry.v1.PullProjectDataResponse.stations:type_name -> geoquerry.v1.Station
	7,  // 12: geoquerry.v1.PullProjectDataResponse.measurements:type_name -> geoquerry.v1.StructuralMeasurement
	8,  // 13: geoquerry.v1.PullProjectDataResponse.samples:type_name -> geoquerry.v1.RockSample
	9,  // 14: geoquerry.v1.PullProjectDataResponse.boreholes:type_name -> geoquerry.v1.Borehole
	10, // 15: geoquerry.v1.PullProjectDataResponse.vegetation:type_name -> geoquerry.v1.Vegetation
	11, // 16: geoquerry.v1.PullProjectDataResponse.concessions:type_name -> geoquerry.v1.ConcessionPolygon
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_sync_proto_init() }
func file_geoquerry_v1_sync_proto_init() {
	if File_geoquerry_v1_sync_proto != nil {
		return
	}
	file_geoquerry_v1_geology_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_sync_proto_rawDesc), len(file_geoquerry_v1_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geoquerry_v1_sync_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_sync_proto_depIdxs,
		EnumInfos:         file_geoquerry_v1_sync_proto_enumTypes,
		MessageInfos:      file_geoquerry_v1_sync_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_sync_proto = out.File
	file_geoquerry_v1_sync_proto_goTypes = nil
	file_geoquerry_v1_sync_proto_depIdxs = nil
}
