// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/telemetry.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamLiveTelemetryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName          string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ProjectId         int64                  `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Latitude          float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Elevation         float64                `protobuf:"fixed64,6,opt,name=elevation,proto3" json:"elevation,omitempty"`
	GpsAccuracy       float64                `protobuf:"fixed64,7,opt,name=gps_accuracy,json=gpsAccuracy,proto3" json:"gps_accuracy,omitempty"`
	Heading           float64                `protobuf:"fixed64,8,opt,name=heading,proto3" json:"heading,omitempty"`
	SpeedMps          float64                `protobuf:"fixed64,9,opt,name=speed_mps,json=speedMps,proto3" json:"speed_mps,omitempty"`
	BatteryPercentage int32                  `protobuf:"varint,10,opt,name=battery_percentage,json=batteryPercentage,proto3" json:"battery_percentage,omitempty"`
	RecordedAt        int64                  `protobuf:"varint,11,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamLiveTelemetryRequest) Reset() {
	*x = StreamLiveTelemetryRequest{}
	mi := &file_geoquerry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLiveTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLiveTelemetryRequest) ProtoMessage() {}

func (x *StreamLiveTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLiveTelemetryRequest.ProtoReflect.Descriptor instead.
func (*StreamLiveTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *StreamLiveTelemetryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamLiveTelemetryRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *StreamLiveTelemetryRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *StreamLiveTelemetryRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *StreamLiveTelemetryRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *StreamLiveTelemetryRequest) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

func (x *StreamLiveTelemetryRequest) GetGpsAccuracy() float64 {
	if x != nil {
		return x.GpsAccuracy
	}
	return 0
}

func (x *StreamLiveTelemetryRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *StreamLiveTelemetryRequest) GetSpeedMps() float64 {
	if x != nil {
		return x.SpeedMps
	}
	return 0
}

func (x *StreamLiveTelemetryRequest) GetBatteryPercentage() int32 {
	if x != nil {
		return x.BatteryPercentage
	}
	return 0
}

func (x *StreamLiveTelemetryRequest) GetRecordedAt() int64 {
	if x != nil {
		return x.RecordedAt
	}
	return 0
}

type TeamMemberLocation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName          string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Latitude          float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Elevation         float64                `protobuf:"fixed64,5,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Heading           float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	BatteryPercentage int32                  `protobuf:"varint,7,opt,name=battery_percentage,json=batteryPercentage,proto3" json:"battery_percentage,omitempty"`
	LastSeenAt        int64                  `protobuf:"varint,8,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	IsActive          bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TeamMemberLocation) Reset() {
	*x = TeamMemberLocation{}
	mi := &file_geoquerry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMemberLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMemberLocation) ProtoMessage() {}

func (x *TeamMemberLocation) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMemberLocation.ProtoReflect.Descriptor instead.
func (*TeamMemberLocation) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TeamMemberLocation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamMemberLocation) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *TeamMemberLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TeamMemberLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TeamMemberLocation) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

func (x *TeamMemberLocation) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *TeamMemberLocation) GetBatteryPercentage() int32 {
	if x != nil {
		return x.BatteryPercentage
	}
	return 0
}

func (x *TeamMemberLocation) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *TeamMemberLocation) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type StreamLiveTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Members       []*TeamMemberLocation  `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLiveTelemetryResponse) Reset() {
	*x = StreamLiveTelemetryResponse{}
	mi := &file_geoquerry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLiveTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLiveTelemetryResponse) ProtoMessage() {}

func (x *StreamLiveTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLiveTelemetryResponse.ProtoReflect.Descriptor instead.
func (*StreamLiveTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *StreamLiveTelemetryResponse) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *StreamLiveTelemetryResponse) GetMembers() []*TeamMemberLocation {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_geoquerry_v1_telemetry_proto protoreflect.FileDescriptor

const file_geoquerry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1cgeoquerry/v1/telemetry.proto\x12\fgeoquerry.v1\"\xf3\x02\n" +
	"\x1aStreamLiveTelemetryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x03R\tprojectId\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\televation\x18\x06 \x01(\x01R\televation\x12!\n" +
	"\fgps_accuracy\x18\a \x01(\x01R\vgpsAccuracy\x12\x18\n" +
	"\aheading\x18\b \x01(\x01R\aheading\x12\x1b\n" +
	"\tspeed_mps\x18\t \x01(\x01R\bspeedMps\x12-\n" +
	"\x12battery_percentage\x18\n" +
	" \x01(\x05R\x11batteryPercentage\x12\x1f\n" +
	"\vrecorded_at\x18\v \x01(\x03R\n" +
	"recordedAt\"\xaa\x02\n" +
	"\x12TeamMemberLocation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\televation\x18\x05 \x01(\x01R\televation\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12-\n" +
	"\x12battery_percentage\x18\a \x01(\x05R\x11batteryPercentage\x12 \n" +
	"\flast_seen_at\x18\b \x01(\x03R\n" +
	"lastSeenAt\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\"x\n" +
	"\x1bStreamLiveTelemetryResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12:\n" +
	"\amembers\x18\x02 \x03(\v2 .geoquerry.v1.TeamMemberLocationR\amembersB?Z=gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_telemetry_proto_rawDescOnce sync.Once
	file_geoquerry_v1_telemetry_proto_rawDescData []byte
)

func file_geoquerry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_telemetry_proto_rawDesc), len(file_geoquerry_v1_telemetry_proto_rawDesc)))
	})
	return file_geoquerry_v1_telemetry_proto_rawDescData
}

var file_geoquerry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_geoquerry_v1_telemetry_proto_goTypes = []any{
	(*StreamLiveTelemetryRequest)(nil),  // 0: geoquerry.v1.StreamLiveTelemetryRequest
	(*TeamMemberLocation)(nil),          // 1: geoquerry.v1.TeamMemberLocation
	(*StreamLiveTelemetryResponse)(nil), // 2: geoquerry.v1.StreamLiveTelemetryResponse
}
var file_geoquerry_v1_telemetry_proto_depIdxs = []int32{
	1, // 0: geoquerry.v1.StreamLiveTelemetryResponse.members:type_name -> geoquerry.v1.TeamMemberLocation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_telemetry_proto_init() }
func file_geoquerry_v1_telemetry_proto_init() {
	if File_geoquerry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_telemetry_proto_rawDesc), len(file_geoquerry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geoquerry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_geoquerry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_telemetry_proto = out.File
	file_geoquerry_v1_telemetry_proto_goTypes = nil
	file_geoquerry_v1_telemetry_proto_depIdxs = nil
}
