// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: geoquerry/v1/tenant.proto

package geoquerryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantRole int32

const (
	TenantRole_TENANT_ROLE_UNSPECIFIED TenantRole = 0
	TenantRole_TENANT_ROLE_VIEWER      TenantRole = 1
	TenantRole_TENANT_ROLE_GEOLOGIST   TenantRole = 2
	TenantRole_TENANT_ROLE_ADMIN       TenantRole = 3
	TenantRole_TENANT_ROLE_OWNER       TenantRole = 4
)

// Enum value maps for TenantRole.
var (
	TenantRole_name = map[int32]string{
		0: "TENANT_ROLE_UNSPECIFIED",
		1: "TENANT_ROLE_VIEWER",
		2: "TENANT_ROLE_GEOLOGIST",
		3: "TENANT_ROLE_ADMIN",
		4: "TENANT_ROLE_OWNER",
	}
	TenantRole_value = map[string]int32{
		"TENANT_ROLE_UNSPECIFIED": 0,
		"TENANT_ROLE_VIEWER":      1,
		"TENANT_ROLE_GEOLOGIST":   2,
		"TENANT_ROLE_ADMIN":       3,
		"TENANT_ROLE_OWNER":       4,
	}
)

func (x TenantRole) Enum() *TenantRole {
	p := new(TenantRole)
	*p = x
	return p
}

func (x TenantRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantRole) Descriptor() protoreflect.EnumDescriptor {
	return file_geoquerry_v1_tenant_proto_enumTypes[0].Descriptor()
}

func (TenantRole) Type() protoreflect.EnumType {
	return &file_geoquerry_v1_tenant_proto_enumTypes[0]
}

func (x TenantRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantRole.Descriptor instead.
func (TenantRole) EnumDescriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{0}
}

type OrganizationSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug             string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	CallerRole       TenantRole             `protobuf:"varint,4,opt,name=caller_role,json=callerRole,proto3,enum=geoquerry.v1.TenantRole" json:"caller_role,omitempty"`
	SubscriptionTier string                 `protobuf:"bytes,5,opt,name=subscription_tier,json=subscriptionTier,proto3" json:"subscription_tier,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrganizationSummary) Reset() {
	*x = OrganizationSummary{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationSummary) ProtoMessage() {}

func (x *OrganizationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationSummary.ProtoReflect.Descriptor instead.
func (*OrganizationSummary) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationSummary) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *OrganizationSummary) GetCallerRole() TenantRole {
	if x != nil {
		return x.CallerRole
	}
	return TenantRole_TENANT_ROLE_UNSPECIFIED
}

func (x *OrganizationSummary) GetSubscriptionTier() string {
	if x != nil {
		return x.SubscriptionTier
	}
	return ""
}

func (x *OrganizationSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type OrganizationMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Role          TenantRole             `protobuf:"varint,4,opt,name=role,proto3,enum=geoquerry.v1.TenantRole" json:"role,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMember) Reset() {
	*x = OrganizationMember{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMember) ProtoMessage() {}

func (x *OrganizationMember) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMember.ProtoReflect.Descriptor instead.
func (*OrganizationMember) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *OrganizationMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrganizationMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OrganizationMember) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OrganizationMember) GetRole() TenantRole {
	if x != nil {
		return x.Role
	}
	return TenantRole_TENANT_ROLE_UNSPECIFIED
}

func (x *OrganizationMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type ProjectSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TargetCommodity string                 `protobuf:"bytes,5,opt,name=target_commodity,json=targetCommodity,proto3" json:"target_commodity,omitempty"` // e.g. Gold, Lithium, Copper
	CrsEpsg         string                 `protobuf:"bytes,6,opt,name=crs_epsg,json=crsEpsg,proto3" json:"crs_epsg,omitempty"`                         // e.g. "EPSG:32636" (UTM 36N)
	CreatedAt       int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectSummary) Reset() {
	*x = ProjectSummary{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSummary) ProtoMessage() {}

func (x *ProjectSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSummary.ProtoReflect.Descriptor instead.
func (*ProjectSummary) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectSummary) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ProjectSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectSummary) GetTargetCommodity() string {
	if x != nil {
		return x.TargetCommodity
	}
	return ""
}

func (x *ProjectSummary) GetCrsEpsg() string {
	if x != nil {
		return x.CrsEpsg
	}
	return ""
}

func (x *ProjectSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ProjectSummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListOrganizationsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Pagination    *CursorPaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrganizationsRequest) GetPagination() *CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListOrganizationsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Organizations []*OrganizationSummary    `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Pagination    *CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*OrganizationSummary {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetPagination() *CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *OrganizationSummary   `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrganizationResponse) GetOrganization() *OrganizationSummary {
	if x != nil {
		return x.Organization
	}
	return nil
}

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *OrganizationSummary   `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrganizationResponse) GetOrganization() *OrganizationSummary {
	if x != nil {
		return x.Organization
	}
	return nil
}

type UpdateOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *OrganizationSummary   `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationResponse) Reset() {
	*x = UpdateOrganizationResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationResponse) ProtoMessage() {}

func (x *UpdateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrganizationResponse) GetOrganization() *OrganizationSummary {
	if x != nil {
		return x.Organization
	}
	return nil
}

type TransferOrganizationOwnershipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TargetUserId   string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferOrganizationOwnershipRequest) Reset() {
	*x = TransferOrganizationOwnershipRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOrganizationOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOrganizationOwnershipRequest) ProtoMessage() {}

func (x *TransferOrganizationOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOrganizationOwnershipRequest.ProtoReflect.Descriptor instead.
func (*TransferOrganizationOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *TransferOrganizationOwnershipRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *TransferOrganizationOwnershipRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type TransferOrganizationOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOrganizationOwnershipResponse) Reset() {
	*x = TransferOrganizationOwnershipResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOrganizationOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOrganizationOwnershipResponse) ProtoMessage() {}

func (x *TransferOrganizationOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOrganizationOwnershipResponse.ProtoReflect.Descriptor instead.
func (*TransferOrganizationOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *TransferOrganizationOwnershipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMembersRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	OrganizationId string                   `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Pagination     *CursorPaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *ListMembersRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListMembersRequest) GetPagination() *CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMembersResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Members       []*OrganizationMember     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *ListMembersResponse) GetMembers() []*OrganizationMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetPagination() *CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type InviteMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RequestedRole  TenantRole             `protobuf:"varint,3,opt,name=requested_role,json=requestedRole,proto3,enum=geoquerry.v1.TenantRole" json:"requested_role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InviteMemberRequest) Reset() {
	*x = InviteMemberRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberRequest) ProtoMessage() {}

func (x *InviteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteMemberRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{15}
}

func (x *InviteMemberRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *InviteMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteMemberRequest) GetRequestedRole() TenantRole {
	if x != nil {
		return x.RequestedRole
	}
	return TenantRole_TENANT_ROLE_UNSPECIFIED
}

type InviteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberResponse) Reset() {
	*x = InviteMemberResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberResponse) ProtoMessage() {}

func (x *InviteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteMemberResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{16}
}

func (x *InviteMemberResponse) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type UpdateMemberRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TargetUserId   string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	NewRole        TenantRole             `protobuf:"varint,3,opt,name=new_role,json=newRole,proto3,enum=geoquerry.v1.TenantRole" json:"new_role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMemberRoleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetNewRole() TenantRole {
	if x != nil {
		return x.NewRole
	}
	return TenantRole_TENANT_ROLE_UNSPECIFIED
}

type UpdateMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleResponse) Reset() {
	*x = UpdateMemberRoleResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleResponse) ProtoMessage() {}

func (x *UpdateMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateMemberRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TargetUserId   string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveMemberRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RemoveMemberRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListProjectsRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	OrganizationId string                   `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Pagination     *CursorPaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{21}
}

func (x *ListProjectsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListProjectsRequest) GetPagination() *CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Projects      []*ProjectSummary         `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Pagination    *CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{22}
}

func (x *ListProjectsResponse) GetProjects() []*ProjectSummary {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetPagination() *CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{23}
}

func (x *GetProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *ProjectSummary        `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{24}
}

func (x *GetProjectResponse) GetProject() *ProjectSummary {
	if x != nil {
		return x.Project
	}
	return nil
}

type CreateProjectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TargetCommodity string                 `protobuf:"bytes,4,opt,name=target_commodity,json=targetCommodity,proto3" json:"target_commodity,omitempty"`
	CrsEpsg         string                 `protobuf:"bytes,5,opt,name=crs_epsg,json=crsEpsg,proto3" json:"crs_epsg,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{25}
}

func (x *CreateProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetTargetCommodity() string {
	if x != nil {
		return x.TargetCommodity
	}
	return ""
}

func (x *CreateProjectRequest) GetCrsEpsg() string {
	if x != nil {
		return x.CrsEpsg
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *ProjectSummary        `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{26}
}

func (x *CreateProjectResponse) GetProject() *ProjectSummary {
	if x != nil {
		return x.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TargetCommodity string                 `protobuf:"bytes,5,opt,name=target_commodity,json=targetCommodity,proto3" json:"target_commodity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetTargetCommodity() string {
	if x != nil {
		return x.TargetCommodity
	}
	return ""
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *ProjectSummary        `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateProjectResponse) GetProject() *ProjectSummary {
	if x != nil {
		return x.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DeleteProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoquerry_v1_tenant_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_geoquerry_v1_tenant_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteProjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_geoquerry_v1_tenant_proto protoreflect.FileDescriptor

const file_geoquerry_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"\x19geoquerry/v1/tenant.proto\x12\fgeoquerry.v1\x1a\x19geoquerry/v1/common.proto\"\xd4\x01\n" +
	"\x13OrganizationSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x129\n" +
	"\vcaller_role\x18\x04 \x01(\x0e2\x18.geoquerry.v1.TenantRoleR\n" +
	"callerRole\x12+\n" +
	"\x11subscription_tier\x18\x05 \x01(\tR\x10subscriptionTier\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\xb1\x01\n" +
	"\x12OrganizationMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12,\n" +
	"\x04role\x18\x04 \x01(\x0e2\x18.geoquerry.v1.TenantRoleR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt\"\x83\x02\n" +
	"\x0eProjectSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12)\n" +
	"\x10target_commodity\x18\x05 \x01(\tR\x0ftargetCommodity\x12\x19\n" +
	"\bcrs_epsg\x18\x06 \x01(\tR\acrsEpsg\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"a\n" +
	"\x18ListOrganizationsRequest\x12E\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2%.geoquerry.v1.CursorPaginationRequestR\n" +
	"pagination\"\xac\x01\n" +
	"\x19ListOrganizationsResponse\x12G\n" +
	"\rorganizations\x18\x01 \x03(\v2!.geoquerry.v1.OrganizationSummaryR\rorganizations\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.geoquerry.v1.CursorPaginationResponseR\n" +
	"pagination\"A\n" +
	"\x16GetOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"`\n" +
	"\x17GetOrganizationResponse\x12E\n" +
	"\forganization\x18\x01 \x01(\v2!.geoquerry.v1.OrganizationSummaryR\forganization\"C\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"c\n" +
	"\x1aCreateOrganizationResponse\x12E\n" +
	"\forganization\x18\x01 \x01(\v2!.geoquerry.v1.OrganizationSummaryR\forganization\"X\n" +
	"\x19UpdateOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"c\n" +
	"\x1aUpdateOrganizationResponse\x12E\n" +
	"\forganization\x18\x01 \x01(\v2!.geoquerry.v1.OrganizationSummaryR\forganization\"u\n" +
	"$TransferOrganizationOwnershipRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"A\n" +
	"%TransferOrganizationOwnershipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x84\x01\n" +
	"\x12ListMembersRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12E\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2%.geoquerry.v1.CursorPaginationRequestR\n" +
	"pagination\"\x99\x01\n" +
	"\x13ListMembersResponse\x12:\n" +
	"\amembers\x18\x01 \x03(\v2 .geoquerry.v1.OrganizationMemberR\amembers\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.geoquerry.v1.CursorPaginationResponseR\n" +
	"pagination\"\x95\x01\n" +
	"\x13InviteMemberRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12?\n" +
	"\x0erequested_role\x18\x03 \x01(\x0e2\x18.geoquerry.v1.TenantRoleR\rrequestedRole\";\n" +
	"\x14InviteMemberResponse\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\"\x9d\x01\n" +
	"\x17UpdateMemberRoleRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x123\n" +
	"\bnew_role\x18\x03 \x01(\x0e2\x18.geoquerry.v1.TenantRoleR\anewRole\"4\n" +
	"\x18UpdateMemberRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"d\n" +
	"\x13RemoveMemberRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"0\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x85\x01\n" +
	"\x13ListProjectsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12E\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2%.geoquerry.v1.CursorPaginationRequestR\n" +
	"pagination\"\x98\x01\n" +
	"\x14ListProjectsResponse\x128\n" +
	"\bprojects\x18\x01 \x03(\v2\x1c.geoquerry.v1.ProjectSummaryR\bprojects\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.geoquerry.v1.CursorPaginationResponseR\n" +
	"pagination\"[\n" +
	"\x11GetProjectRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"L\n" +
	"\x12GetProjectResponse\x126\n" +
	"\aproject\x18\x01 \x01(\v2\x1c.geoquerry.v1.ProjectSummaryR\aproject\"\xbb\x01\n" +
	"\x14CreateProjectRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10target_commodity\x18\x04 \x01(\tR\x0ftargetCommodity\x12\x19\n" +
	"\bcrs_epsg\x18\x05 \x01(\tR\acrsEpsg\"O\n" +
	"\x15CreateProjectResponse\x126\n" +
	"\aproject\x18\x01 \x01(\v2\x1c.geoquerry.v1.ProjectSummaryR\aproject\"\xbf\x01\n" +
	"\x14UpdateProjectRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12)\n" +
	"\x10target_commodity\x18\x05 \x01(\tR\x0ftargetCommodity\"O\n" +
	"\x15UpdateProjectResponse\x126\n" +
	"\aproject\x18\x01 \x01(\v2\x1c.geoquerry.v1.ProjectSummaryR\aproject\"^\n" +
	"\x14DeleteProjectRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"1\n" +
	"\x15DeleteProjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x8a\x01\n" +
	"\n" +
	"TenantRole\x12\x1b\n" +
	"\x17TENANT_ROLE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TENANT_ROLE_VIEWER\x10\x01\x12\x19\n" +
	"\x15TENANT_ROLE_GEOLOGIST\x10\x02\x12\x15\n" +
	"\x11TENANT_ROLE_ADMIN\x10\x03\x12\x15\n" +
	"\x11TENANT_ROLE_OWNER\x10\x042\xcd\n" +
	"\n" +
	"\rTenantService\x12d\n" +
	"\x11ListOrganizations\x12&.geoquerry.v1.ListOrganizationsRequest\x1a'.geoquerry.v1.ListOrganizationsResponse\x12^\n" +
	"\x0fGetOrganization\x12$.geoquerry.v1.GetOrganizationRequest\x1a%.geoquerry.v1.GetOrganizationResponse\x12g\n" +
	"\x12CreateOrganization\x12'.geoquerry.v1.CreateOrganizationRequest\x1a(.geoquerry.v1.CreateOrganizationResponse\x12g\n" +
	"\x12UpdateOrganization\x12'.geoquerry.v1.UpdateOrganizationRequest\x1a(.geoquerry.v1.UpdateOrganizationResponse\x12\x88\x01\n" +
	"\x1dTransferOrganizationOwnership\x122.geoquerry.v1.TransferOrganizationOwnershipRequest\x1a3.geoquerry.v1.TransferOrganizationOwnershipResponse\x12R\n" +
	"\vListMembers\x12 .geoquerry.v1.ListMembersRequest\x1a!.geoquerry.v1.ListMembersResponse\x12U\n" +
	"\fInviteMember\x12!.geoquerry.v1.InviteMemberRequest\x1a\".geoquerry.v1.InviteMemberResponse\x12a\n" +
	"\x10UpdateMemberRole\x12%.geoquerry.v1.UpdateMemberRoleRequest\x1a&.geoquerry.v1.UpdateMemberRoleResponse\x12U\n" +
	"\fRemoveMember\x12!.geoquerry.v1.RemoveMemberRequest\x1a\".geoquerry.v1.RemoveMemberResponse\x12U\n" +
	"\fListProjects\x12!.geoquerry.v1.ListProjectsRequest\x1a\".geoquerry.v1.ListProjectsResponse\x12O\n" +
	"\n" +
	"GetProject\x12\x1f.geoquerry.v1.GetProjectRequest\x1a .geoquerry.v1.GetProjectResponse\x12X\n" +
	"\rCreateProject\x12\".geoquerry.v1.CreateProjectRequest\x1a#.geoquerry.v1.CreateProjectResponse\x12X\n" +
	"\rUpdateProject\x12\".geoquerry.v1.UpdateProjectRequest\x1a#.geoquerry.v1.UpdateProjectResponse\x12X\n" +
	"\rDeleteProject\x12\".geoquerry.v1.DeleteProjectRequest\x1a#.geoquerry.v1.DeleteProjectResponseBLZJgitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1;geoquerryv1b\x06proto3"

var (
	file_geoquerry_v1_tenant_proto_rawDescOnce sync.Once
	file_geoquerry_v1_tenant_proto_rawDescData []byte
)

func file_geoquerry_v1_tenant_proto_rawDescGZIP() []byte {
	file_geoquerry_v1_tenant_proto_rawDescOnce.Do(func() {
		file_geoquerry_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoquerry_v1_tenant_proto_rawDesc), len(file_geoquerry_v1_tenant_proto_rawDesc)))
	})
	return file_geoquerry_v1_tenant_proto_rawDescData
}

var file_geoquerry_v1_tenant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_geoquerry_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_geoquerry_v1_tenant_proto_goTypes = []any{
	(TenantRole)(0),                               // 0: geoquerry.v1.TenantRole
	(*OrganizationSummary)(nil),                   // 1: geoquerry.v1.OrganizationSummary
	(*OrganizationMember)(nil),                    // 2: geoquerry.v1.OrganizationMember
	(*ProjectSummary)(nil),                        // 3: geoquerry.v1.ProjectSummary
	(*ListOrganizationsRequest)(nil),              // 4: geoquerry.v1.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil),             // 5: geoquerry.v1.ListOrganizationsResponse
	(*GetOrganizationRequest)(nil),                // 6: geoquerry.v1.GetOrganizationRequest
	(*GetOrganizationResponse)(nil),               // 7: geoquerry.v1.GetOrganizationResponse
	(*CreateOrganizationRequest)(nil),             // 8: geoquerry.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil),            // 9: geoquerry.v1.CreateOrganizationResponse
	(*UpdateOrganizationRequest)(nil),             // 10: geoquerry.v1.UpdateOrganizationRequest
	(*UpdateOrganizationResponse)(nil),            // 11: geoquerry.v1.UpdateOrganizationResponse
	(*TransferOrganizationOwnershipRequest)(nil),  // 12: geoquerry.v1.TransferOrganizationOwnershipRequest
	(*TransferOrganizationOwnershipResponse)(nil), // 13: geoquerry.v1.TransferOrganizationOwnershipResponse
	(*ListMembersRequest)(nil),                    // 14: geoquerry.v1.ListMembersRequest
	(*ListMembersResponse)(nil),                   // 15: geoquerry.v1.ListMembersResponse
	(*InviteMemberRequest)(nil),                   // 16: geoquerry.v1.InviteMemberRequest
	(*InviteMemberResponse)(nil),                  // 17: geoquerry.v1.InviteMemberResponse
	(*UpdateMemberRoleRequest)(nil),               // 18: geoquerry.v1.UpdateMemberRoleRequest
	(*UpdateMemberRoleResponse)(nil),              // 19: geoquerry.v1.UpdateMemberRoleResponse
	(*RemoveMemberRequest)(nil),                   // 20: geoquerry.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),                  // 21: geoquerry.v1.RemoveMemberResponse
	(*ListProjectsRequest)(nil),                   // 22: geoquerry.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),                  // 23: geoquerry.v1.ListProjectsResponse
	(*GetProjectRequest)(nil),                     // 24: geoquerry.v1.GetProjectRequest
	(*GetProjectResponse)(nil),                    // 25: geoquerry.v1.GetProjectResponse
	(*CreateProjectRequest)(nil),                  // 26: geoquerry.v1.CreateProjectRequest
	(*CreateProjectResponse)(nil),                 // 27: geoquerry.v1.CreateProjectResponse
	(*UpdateProjectRequest)(nil),                  // 28: geoquerry.v1.UpdateProjectRequest
	(*UpdateProjectResponse)(nil),                 // 29: geoquerry.v1.UpdateProjectResponse
	(*DeleteProjectRequest)(nil),                  // 30: geoquerry.v1.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),                 // 31: geoquerry.v1.DeleteProjectResponse
	(*CursorPaginationRequest)(nil),               // 32: geoquerry.v1.CursorPaginationRequest
	(*CursorPaginationResponse)(nil),              // 33: geoquerry.v1.CursorPaginationResponse
}
var file_geoquerry_v1_tenant_proto_depIdxs = []int32{
	0,  // 0: geoquerry.v1.OrganizationSummary.caller_role:type_name -> geoquerry.v1.TenantRole
	0,  // 1: geoquerry.v1.OrganizationMember.role:type_name -> geoquerry.v1.TenantRole
	32, // 2: geoquerry.v1.ListOrganizationsRequest.pagination:type_name -> geoquerry.v1.CursorPaginationRequest
	1,  // 3: geoquerry.v1.ListOrganizationsResponse.organizations:type_name -> geoquerry.v1.OrganizationSummary
	33, // 4: geoquerry.v1.ListOrganizationsResponse.pagination:type_name -> geoquerry.v1.CursorPaginationResponse
	1,  // 5: geoquerry.v1.GetOrganizationResponse.organization:type_name -> geoquerry.v1.OrganizationSummary
	1,  // 6: geoquerry.v1.CreateOrganizationResponse.organization:type_name -> geoquerry.v1.OrganizationSummary
	1,  // 7: geoquerry.v1.UpdateOrganizationResponse.organization:type_name -> geoquerry.v1.OrganizationSummary
	32, // 8: geoquerry.v1.ListMembersRequest.pagination:type_name -> geoquerry.v1.CursorPaginationRequest
	2,  // 9: geoquerry.v1.ListMembersResponse.members:type_name -> geoquerry.v1.OrganizationMember
	33, // 10: geoquerry.v1.ListMembersResponse.pagination:type_name -> geoquerry.v1.CursorPaginationResponse
	0,  // 11: geoquerry.v1.InviteMemberRequest.requested_role:type_name -> geoquerry.v1.TenantRole
	0,  // 12: geoquerry.v1.UpdateMemberRoleRequest.new_role:type_name -> geoquerry.v1.TenantRole
	32, // 13: geoquerry.v1.ListProjectsRequest.pagination:type_name -> geoquerry.v1.CursorPaginationRequest
	3,  // 14: geoquerry.v1.ListProjectsResponse.projects:type_name -> geoquerry.v1.ProjectSummary
	33, // 15: geoquerry.v1.ListProjectsResponse.pagination:type_name -> geoquerry.v1.CursorPaginationResponse
	3,  // 16: geoquerry.v1.GetProjectResponse.project:type_name -> geoquerry.v1.ProjectSummary
	3,  // 17: geoquerry.v1.CreateProjectResponse.project:type_name -> geoquerry.v1.ProjectSummary
	3,  // 18: geoquerry.v1.UpdateProjectResponse.project:type_name -> geoquerry.v1.ProjectSummary
	4,  // 19: geoquerry.v1.TenantService.ListOrganizations:input_type -> geoquerry.v1.ListOrganizationsRequest
	6,  // 20: geoquerry.v1.TenantService.GetOrganization:input_type -> geoquerry.v1.GetOrganizationRequest
	8,  // 21: geoquerry.v1.TenantService.CreateOrganization:input_type -> geoquerry.v1.CreateOrganizationRequest
	10, // 22: geoquerry.v1.TenantService.UpdateOrganization:input_type -> geoquerry.v1.UpdateOrganizationRequest
	12, // 23: geoquerry.v1.TenantService.TransferOrganizationOwnership:input_type -> geoquerry.v1.TransferOrganizationOwnershipRequest
	14, // 24: geoquerry.v1.TenantService.ListMembers:input_type -> geoquerry.v1.ListMembersRequest
	16, // 25: geoquerry.v1.TenantService.InviteMember:input_type -> geoquerry.v1.InviteMemberRequest
	18, // 26: geoquerry.v1.TenantService.UpdateMemberRole:input_type -> geoquerry.v1.UpdateMemberRoleRequest
	20, // 27: geoquerry.v1.TenantService.RemoveMember:input_type -> geoquerry.v1.RemoveMemberRequest
	22, // 28: geoquerry.v1.TenantService.ListProjects:input_type -> geoquerry.v1.ListProjectsRequest
	24, // 29: geoquerry.v1.TenantService.GetProject:input_type -> geoquerry.v1.GetProjectRequest
	26, // 30: geoquerry.v1.TenantService.CreateProject:input_type -> geoquerry.v1.CreateProjectRequest
	28, // 31: geoquerry.v1.TenantService.UpdateProject:input_type -> geoquerry.v1.UpdateProjectRequest
	30, // 32: geoquerry.v1.TenantService.DeleteProject:input_type -> geoquerry.v1.DeleteProjectRequest
	5,  // 33: geoquerry.v1.TenantService.ListOrganizations:output_type -> geoquerry.v1.ListOrganizationsResponse
	7,  // 34: geoquerry.v1.TenantService.GetOrganization:output_type -> geoquerry.v1.GetOrganizationResponse
	9,  // 35: geoquerry.v1.TenantService.CreateOrganization:output_type -> geoquerry.v1.CreateOrganizationResponse
	11, // 36: geoquerry.v1.TenantService.UpdateOrganization:output_type -> geoquerry.v1.UpdateOrganizationResponse
	13, // 37: geoquerry.v1.TenantService.TransferOrganizationOwnership:output_type -> geoquerry.v1.TransferOrganizationOwnershipResponse
	15, // 38: geoquerry.v1.TenantService.ListMembers:output_type -> geoquerry.v1.ListMembersResponse
	17, // 39: geoquerry.v1.TenantService.InviteMember:output_type -> geoquerry.v1.InviteMemberResponse
	19, // 40: geoquerry.v1.TenantService.UpdateMemberRole:output_type -> geoquerry.v1.UpdateMemberRoleResponse
	21, // 41: geoquerry.v1.TenantService.RemoveMember:output_type -> geoquerry.v1.RemoveMemberResponse
	23, // 42: geoquerry.v1.TenantService.ListProjects:output_type -> geoquerry.v1.ListProjectsResponse
	25, // 43: geoquerry.v1.TenantService.GetProject:output_type -> geoquerry.v1.GetProjectResponse
	27, // 44: geoquerry.v1.TenantService.CreateProject:output_type -> geoquerry.v1.CreateProjectResponse
	29, // 45: geoquerry.v1.TenantService.UpdateProject:output_type -> geoquerry.v1.UpdateProjectResponse
	31, // 46: geoquerry.v1.TenantService.DeleteProject:output_type -> geoquerry.v1.DeleteProjectResponse
	33, // [33:47] is the sub-list for method output_type
	19, // [19:33] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_geoquerry_v1_tenant_proto_init() }
func file_geoquerry_v1_tenant_proto_init() {
	if File_geoquerry_v1_tenant_proto != nil {
		return
	}
	file_geoquerry_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoquerry_v1_tenant_proto_rawDesc), len(file_geoquerry_v1_tenant_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geoquerry_v1_tenant_proto_goTypes,
		DependencyIndexes: file_geoquerry_v1_tenant_proto_depIdxs,
		EnumInfos:         file_geoquerry_v1_tenant_proto_enumTypes,
		MessageInfos:      file_geoquerry_v1_tenant_proto_msgTypes,
	}.Build()
	File_geoquerry_v1_tenant_proto = out.File
	file_geoquerry_v1_tenant_proto_goTypes = nil
	file_geoquerry_v1_tenant_proto_depIdxs = nil
}
