// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: geoquerry/v1/auth.proto

package geoquerryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "geoquerry.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceExchangeAssertionProcedure is the fully-qualified name of the AuthService's
	// ExchangeAssertion RPC.
	AuthServiceExchangeAssertionProcedure = "/geoquerry.v1.AuthService/ExchangeAssertion"
	// AuthServiceVerifySudoProcedure is the fully-qualified name of the AuthService's VerifySudo RPC.
	AuthServiceVerifySudoProcedure = "/geoquerry.v1.AuthService/VerifySudo"
	// AuthServiceGetSessionContextProcedure is the fully-qualified name of the AuthService's
	// GetSessionContext RPC.
	AuthServiceGetSessionContextProcedure = "/geoquerry.v1.AuthService/GetSessionContext"
)

// AuthServiceClient is a client for the geoquerry.v1.AuthService service.
type AuthServiceClient interface {
	// ExchangeAssertion validates a Next.js Ed25519 internal assertion and returns
	// the caller's active user context and accessible organizations.
	ExchangeAssertion(context.Context, *connect.Request[v1.ExchangeAssertionRequest]) (*connect.Response[v1.ExchangeAssertionResponse], error)
	// VerifySudo elevates the active session into sudo mode for 15 minutes upon password or MFA verification.
	VerifySudo(context.Context, *connect.Request[v1.VerifySudoRequest]) (*connect.Response[v1.VerifySudoResponse], error)
	// GetSessionContext queries active session claims, permissions, and sudo state.
	GetSessionContext(context.Context, *connect.Request[v1.GetSessionContextRequest]) (*connect.Response[v1.GetSessionContextResponse], error)
}

// NewAuthServiceClient constructs a client for the geoquerry.v1.AuthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_geoquerry_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		exchangeAssertion: connect.NewClient[v1.ExchangeAssertionRequest, v1.ExchangeAssertionResponse](
			httpClient,
			baseURL+AuthServiceExchangeAssertionProcedure,
			connect.WithSchema(authServiceMethods.ByName("ExchangeAssertion")),
			connect.WithClientOptions(opts...),
		),
		verifySudo: connect.NewClient[v1.VerifySudoRequest, v1.VerifySudoResponse](
			httpClient,
			baseURL+AuthServiceVerifySudoProcedure,
			connect.WithSchema(authServiceMethods.ByName("VerifySudo")),
			connect.WithClientOptions(opts...),
		),
		getSessionContext: connect.NewClient[v1.GetSessionContextRequest, v1.GetSessionContextResponse](
			httpClient,
			baseURL+AuthServiceGetSessionContextProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetSessionContext")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	exchangeAssertion *connect.Client[v1.ExchangeAssertionRequest, v1.ExchangeAssertionResponse]
	verifySudo        *connect.Client[v1.VerifySudoRequest, v1.VerifySudoResponse]
	getSessionContext *connect.Client[v1.GetSessionContextRequest, v1.GetSessionContextResponse]
}

// ExchangeAssertion calls geoquerry.v1.AuthService.ExchangeAssertion.
func (c *authServiceClient) ExchangeAssertion(ctx context.Context, req *connect.Request[v1.ExchangeAssertionRequest]) (*connect.Response[v1.ExchangeAssertionResponse], error) {
	return c.exchangeAssertion.CallUnary(ctx, req)
}

// VerifySudo calls geoquerry.v1.AuthService.VerifySudo.
func (c *authServiceClient) VerifySudo(ctx context.Context, req *connect.Request[v1.VerifySudoRequest]) (*connect.Response[v1.VerifySudoResponse], error) {
	return c.verifySudo.CallUnary(ctx, req)
}

// GetSessionContext calls geoquerry.v1.AuthService.GetSessionContext.
func (c *authServiceClient) GetSessionContext(ctx context.Context, req *connect.Request[v1.GetSessionContextRequest]) (*connect.Response[v1.GetSessionContextResponse], error) {
	return c.getSessionContext.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the geoquerry.v1.AuthService service.
type AuthServiceHandler interface {
	// ExchangeAssertion validates a Next.js Ed25519 internal assertion and returns
	// the caller's active user context and accessible organizations.
	ExchangeAssertion(context.Context, *connect.Request[v1.ExchangeAssertionRequest]) (*connect.Response[v1.ExchangeAssertionResponse], error)
	// VerifySudo elevates the active session into sudo mode for 15 minutes upon password or MFA verification.
	VerifySudo(context.Context, *connect.Request[v1.VerifySudoRequest]) (*connect.Response[v1.VerifySudoResponse], error)
	// GetSessionContext queries active session claims, permissions, and sudo state.
	GetSessionContext(context.Context, *connect.Request[v1.GetSessionContextRequest]) (*connect.Response[v1.GetSessionContextResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_geoquerry_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceExchangeAssertionHandler := connect.NewUnaryHandler(
		AuthServiceExchangeAssertionProcedure,
		svc.ExchangeAssertion,
		connect.WithSchema(authServiceMethods.ByName("ExchangeAssertion")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceVerifySudoHandler := connect.NewUnaryHandler(
		AuthServiceVerifySudoProcedure,
		svc.VerifySudo,
		connect.WithSchema(authServiceMethods.ByName("VerifySudo")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetSessionContextHandler := connect.NewUnaryHandler(
		AuthServiceGetSessionContextProcedure,
		svc.GetSessionContext,
		connect.WithSchema(authServiceMethods.ByName("GetSessionContext")),
		connect.WithHandlerOptions(opts...),
	)
	return "/geoquerry.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceExchangeAssertionProcedure:
			authServiceExchangeAssertionHandler.ServeHTTP(w, r)
		case AuthServiceVerifySudoProcedure:
			authServiceVerifySudoHandler.ServeHTTP(w, r)
		case AuthServiceGetSessionContextProcedure:
			authServiceGetSessionContextHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) ExchangeAssertion(context.Context, *connect.Request[v1.ExchangeAssertionRequest]) (*connect.Response[v1.ExchangeAssertionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.AuthService.ExchangeAssertion is not implemented"))
}

func (UnimplementedAuthServiceHandler) VerifySudo(context.Context, *connect.Request[v1.VerifySudoRequest]) (*connect.Response[v1.VerifySudoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.AuthService.VerifySudo is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetSessionContext(context.Context, *connect.Request[v1.GetSessionContextRequest]) (*connect.Response[v1.GetSessionContextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.AuthService.GetSessionContext is not implemented"))
}
