// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: geoquerry/v1/billing.proto

package geoquerryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BillingServiceName is the fully-qualified name of the BillingService service.
	BillingServiceName = "geoquerry.v1.BillingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BillingServiceGetPriceCatalogProcedure is the fully-qualified name of the BillingService's
	// GetPriceCatalog RPC.
	BillingServiceGetPriceCatalogProcedure = "/geoquerry.v1.BillingService/GetPriceCatalog"
	// BillingServiceInitiateMpesaStkPushProcedure is the fully-qualified name of the BillingService's
	// InitiateMpesaStkPush RPC.
	BillingServiceInitiateMpesaStkPushProcedure = "/geoquerry.v1.BillingService/InitiateMpesaStkPush"
	// BillingServiceCreateStripeCheckoutSessionProcedure is the fully-qualified name of the
	// BillingService's CreateStripeCheckoutSession RPC.
	BillingServiceCreateStripeCheckoutSessionProcedure = "/geoquerry.v1.BillingService/CreateStripeCheckoutSession"
	// BillingServiceGetSubscriptionStatusProcedure is the fully-qualified name of the BillingService's
	// GetSubscriptionStatus RPC.
	BillingServiceGetSubscriptionStatusProcedure = "/geoquerry.v1.BillingService/GetSubscriptionStatus"
)

// BillingServiceClient is a client for the geoquerry.v1.BillingService service.
type BillingServiceClient interface {
	// GetPriceCatalog returns the server-authoritative pricing tiers.
	GetPriceCatalog(context.Context, *connect.Request[v1.GetPriceCatalogRequest]) (*connect.Response[v1.GetPriceCatalogResponse], error)
	// InitiateMpesaStkPush starts an STK push transaction to the specified phone number for a plan.
	InitiateMpesaStkPush(context.Context, *connect.Request[v1.InitiateMpesaStkPushRequest]) (*connect.Response[v1.InitiateMpesaStkPushResponse], error)
	// CreateStripeCheckoutSession creates a hosted Stripe checkout session for an organization.
	CreateStripeCheckoutSession(context.Context, *connect.Request[v1.CreateStripeCheckoutSessionRequest]) (*connect.Response[v1.CreateStripeCheckoutSessionResponse], error)
	// GetSubscriptionStatus queries current plan and active entitlements for an organization.
	GetSubscriptionStatus(context.Context, *connect.Request[v1.GetSubscriptionStatusRequest]) (*connect.Response[v1.GetSubscriptionStatusResponse], error)
}

// NewBillingServiceClient constructs a client for the geoquerry.v1.BillingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBillingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BillingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	billingServiceMethods := v1.File_geoquerry_v1_billing_proto.Services().ByName("BillingService").Methods()
	return &billingServiceClient{
		getPriceCatalog: connect.NewClient[v1.GetPriceCatalogRequest, v1.GetPriceCatalogResponse](
			httpClient,
			baseURL+BillingServiceGetPriceCatalogProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetPriceCatalog")),
			connect.WithClientOptions(opts...),
		),
		initiateMpesaStkPush: connect.NewClient[v1.InitiateMpesaStkPushRequest, v1.InitiateMpesaStkPushResponse](
			httpClient,
			baseURL+BillingServiceInitiateMpesaStkPushProcedure,
			connect.WithSchema(billingServiceMethods.ByName("InitiateMpesaStkPush")),
			connect.WithClientOptions(opts...),
		),
		createStripeCheckoutSession: connect.NewClient[v1.CreateStripeCheckoutSessionRequest, v1.CreateStripeCheckoutSessionResponse](
			httpClient,
			baseURL+BillingServiceCreateStripeCheckoutSessionProcedure,
			connect.WithSchema(billingServiceMethods.ByName("CreateStripeCheckoutSession")),
			connect.WithClientOptions(opts...),
		),
		getSubscriptionStatus: connect.NewClient[v1.GetSubscriptionStatusRequest, v1.GetSubscriptionStatusResponse](
			httpClient,
			baseURL+BillingServiceGetSubscriptionStatusProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetSubscriptionStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// billingServiceClient implements BillingServiceClient.
type billingServiceClient struct {
	getPriceCatalog             *connect.Client[v1.GetPriceCatalogRequest, v1.GetPriceCatalogResponse]
	initiateMpesaStkPush        *connect.Client[v1.InitiateMpesaStkPushRequest, v1.InitiateMpesaStkPushResponse]
	createStripeCheckoutSession *connect.Client[v1.CreateStripeCheckoutSessionRequest, v1.CreateStripeCheckoutSessionResponse]
	getSubscriptionStatus       *connect.Client[v1.GetSubscriptionStatusRequest, v1.GetSubscriptionStatusResponse]
}

// GetPriceCatalog calls geoquerry.v1.BillingService.GetPriceCatalog.
func (c *billingServiceClient) GetPriceCatalog(ctx context.Context, req *connect.Request[v1.GetPriceCatalogRequest]) (*connect.Response[v1.GetPriceCatalogResponse], error) {
	return c.getPriceCatalog.CallUnary(ctx, req)
}

// InitiateMpesaStkPush calls geoquerry.v1.BillingService.InitiateMpesaStkPush.
func (c *billingServiceClient) InitiateMpesaStkPush(ctx context.Context, req *connect.Request[v1.InitiateMpesaStkPushRequest]) (*connect.Response[v1.InitiateMpesaStkPushResponse], error) {
	return c.initiateMpesaStkPush.CallUnary(ctx, req)
}

// CreateStripeCheckoutSession calls geoquerry.v1.BillingService.CreateStripeCheckoutSession.
func (c *billingServiceClient) CreateStripeCheckoutSession(ctx context.Context, req *connect.Request[v1.CreateStripeCheckoutSessionRequest]) (*connect.Response[v1.CreateStripeCheckoutSessionResponse], error) {
	return c.createStripeCheckoutSession.CallUnary(ctx, req)
}

// GetSubscriptionStatus calls geoquerry.v1.BillingService.GetSubscriptionStatus.
func (c *billingServiceClient) GetSubscriptionStatus(ctx context.Context, req *connect.Request[v1.GetSubscriptionStatusRequest]) (*connect.Response[v1.GetSubscriptionStatusResponse], error) {
	return c.getSubscriptionStatus.CallUnary(ctx, req)
}

// BillingServiceHandler is an implementation of the geoquerry.v1.BillingService service.
type BillingServiceHandler interface {
	// GetPriceCatalog returns the server-authoritative pricing tiers.
	GetPriceCatalog(context.Context, *connect.Request[v1.GetPriceCatalogRequest]) (*connect.Response[v1.GetPriceCatalogResponse], error)
	// InitiateMpesaStkPush starts an STK push transaction to the specified phone number for a plan.
	InitiateMpesaStkPush(context.Context, *connect.Request[v1.InitiateMpesaStkPushRequest]) (*connect.Response[v1.InitiateMpesaStkPushResponse], error)
	// CreateStripeCheckoutSession creates a hosted Stripe checkout session for an organization.
	CreateStripeCheckoutSession(context.Context, *connect.Request[v1.CreateStripeCheckoutSessionRequest]) (*connect.Response[v1.CreateStripeCheckoutSessionResponse], error)
	// GetSubscriptionStatus queries current plan and active entitlements for an organization.
	GetSubscriptionStatus(context.Context, *connect.Request[v1.GetSubscriptionStatusRequest]) (*connect.Response[v1.GetSubscriptionStatusResponse], error)
}

// NewBillingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBillingServiceHandler(svc BillingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	billingServiceMethods := v1.File_geoquerry_v1_billing_proto.Services().ByName("BillingService").Methods()
	billingServiceGetPriceCatalogHandler := connect.NewUnaryHandler(
		BillingServiceGetPriceCatalogProcedure,
		svc.GetPriceCatalog,
		connect.WithSchema(billingServiceMethods.ByName("GetPriceCatalog")),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceInitiateMpesaStkPushHandler := connect.NewUnaryHandler(
		BillingServiceInitiateMpesaStkPushProcedure,
		svc.InitiateMpesaStkPush,
		connect.WithSchema(billingServiceMethods.ByName("InitiateMpesaStkPush")),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceCreateStripeCheckoutSessionHandler := connect.NewUnaryHandler(
		BillingServiceCreateStripeCheckoutSessionProcedure,
		svc.CreateStripeCheckoutSession,
		connect.WithSchema(billingServiceMethods.ByName("CreateStripeCheckoutSession")),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetSubscriptionStatusHandler := connect.NewUnaryHandler(
		BillingServiceGetSubscriptionStatusProcedure,
		svc.GetSubscriptionStatus,
		connect.WithSchema(billingServiceMethods.ByName("GetSubscriptionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/geoquerry.v1.BillingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BillingServiceGetPriceCatalogProcedure:
			billingServiceGetPriceCatalogHandler.ServeHTTP(w, r)
		case BillingServiceInitiateMpesaStkPushProcedure:
			billingServiceInitiateMpesaStkPushHandler.ServeHTTP(w, r)
		case BillingServiceCreateStripeCheckoutSessionProcedure:
			billingServiceCreateStripeCheckoutSessionHandler.ServeHTTP(w, r)
		case BillingServiceGetSubscriptionStatusProcedure:
			billingServiceGetSubscriptionStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBillingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBillingServiceHandler struct{}

func (UnimplementedBillingServiceHandler) GetPriceCatalog(context.Context, *connect.Request[v1.GetPriceCatalogRequest]) (*connect.Response[v1.GetPriceCatalogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.BillingService.GetPriceCatalog is not implemented"))
}

func (UnimplementedBillingServiceHandler) InitiateMpesaStkPush(context.Context, *connect.Request[v1.InitiateMpesaStkPushRequest]) (*connect.Response[v1.InitiateMpesaStkPushResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.BillingService.InitiateMpesaStkPush is not implemented"))
}

func (UnimplementedBillingServiceHandler) CreateStripeCheckoutSession(context.Context, *connect.Request[v1.CreateStripeCheckoutSessionRequest]) (*connect.Response[v1.CreateStripeCheckoutSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.BillingService.CreateStripeCheckoutSession is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetSubscriptionStatus(context.Context, *connect.Request[v1.GetSubscriptionStatusRequest]) (*connect.Response[v1.GetSubscriptionStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.BillingService.GetSubscriptionStatus is not implemented"))
}
