// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: geoquerry/v1/gis.proto

package geoquerryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GisIngestionServiceName is the fully-qualified name of the GisIngestionService service.
	GisIngestionServiceName = "geoquerry.v1.GisIngestionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GisIngestionServiceInitiateDatasetUploadProcedure is the fully-qualified name of the
	// GisIngestionService's InitiateDatasetUpload RPC.
	GisIngestionServiceInitiateDatasetUploadProcedure = "/geoquerry.v1.GisIngestionService/InitiateDatasetUpload"
	// GisIngestionServiceCompleteDatasetUploadProcedure is the fully-qualified name of the
	// GisIngestionService's CompleteDatasetUpload RPC.
	GisIngestionServiceCompleteDatasetUploadProcedure = "/geoquerry.v1.GisIngestionService/CompleteDatasetUpload"
	// GisIngestionServiceGetDatasetStatusProcedure is the fully-qualified name of the
	// GisIngestionService's GetDatasetStatus RPC.
	GisIngestionServiceGetDatasetStatusProcedure = "/geoquerry.v1.GisIngestionService/GetDatasetStatus"
	// GisIngestionServiceListDatasetsProcedure is the fully-qualified name of the GisIngestionService's
	// ListDatasets RPC.
	GisIngestionServiceListDatasetsProcedure = "/geoquerry.v1.GisIngestionService/ListDatasets"
)

// GisIngestionServiceClient is a client for the geoquerry.v1.GisIngestionService service.
type GisIngestionServiceClient interface {
	// InitiateDatasetUpload generates a quarantine presigned PUT URL in Cloudflare R2.
	InitiateDatasetUpload(context.Context, *connect.Request[v1.InitiateDatasetUploadRequest]) (*connect.Response[v1.InitiateDatasetUploadResponse], error)
	// CompleteDatasetUpload notifies the backend that upload finished, enqueuing a sandboxed processing job.
	CompleteDatasetUpload(context.Context, *connect.Request[v1.CompleteDatasetUploadRequest]) (*connect.Response[v1.CompleteDatasetUploadResponse], error)
	// GetDatasetStatus polls the ingestion state and extraction summary.
	GetDatasetStatus(context.Context, *connect.Request[v1.GetDatasetStatusRequest]) (*connect.Response[v1.GetDatasetStatusResponse], error)
	// ListDatasets returns verified spatial datasets for a project.
	ListDatasets(context.Context, *connect.Request[v1.ListDatasetsRequest]) (*connect.Response[v1.ListDatasetsResponse], error)
}

// NewGisIngestionServiceClient constructs a client for the geoquerry.v1.GisIngestionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGisIngestionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GisIngestionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gisIngestionServiceMethods := v1.File_geoquerry_v1_gis_proto.Services().ByName("GisIngestionService").Methods()
	return &gisIngestionServiceClient{
		initiateDatasetUpload: connect.NewClient[v1.InitiateDatasetUploadRequest, v1.InitiateDatasetUploadResponse](
			httpClient,
			baseURL+GisIngestionServiceInitiateDatasetUploadProcedure,
			connect.WithSchema(gisIngestionServiceMethods.ByName("InitiateDatasetUpload")),
			connect.WithClientOptions(opts...),
		),
		completeDatasetUpload: connect.NewClient[v1.CompleteDatasetUploadRequest, v1.CompleteDatasetUploadResponse](
			httpClient,
			baseURL+GisIngestionServiceCompleteDatasetUploadProcedure,
			connect.WithSchema(gisIngestionServiceMethods.ByName("CompleteDatasetUpload")),
			connect.WithClientOptions(opts...),
		),
		getDatasetStatus: connect.NewClient[v1.GetDatasetStatusRequest, v1.GetDatasetStatusResponse](
			httpClient,
			baseURL+GisIngestionServiceGetDatasetStatusProcedure,
			connect.WithSchema(gisIngestionServiceMethods.ByName("GetDatasetStatus")),
			connect.WithClientOptions(opts...),
		),
		listDatasets: connect.NewClient[v1.ListDatasetsRequest, v1.ListDatasetsResponse](
			httpClient,
			baseURL+GisIngestionServiceListDatasetsProcedure,
			connect.WithSchema(gisIngestionServiceMethods.ByName("ListDatasets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gisIngestionServiceClient implements GisIngestionServiceClient.
type gisIngestionServiceClient struct {
	initiateDatasetUpload *connect.Client[v1.InitiateDatasetUploadRequest, v1.InitiateDatasetUploadResponse]
	completeDatasetUpload *connect.Client[v1.CompleteDatasetUploadRequest, v1.CompleteDatasetUploadResponse]
	getDatasetStatus      *connect.Client[v1.GetDatasetStatusRequest, v1.GetDatasetStatusResponse]
	listDatasets          *connect.Client[v1.ListDatasetsRequest, v1.ListDatasetsResponse]
}

// InitiateDatasetUpload calls geoquerry.v1.GisIngestionService.InitiateDatasetUpload.
func (c *gisIngestionServiceClient) InitiateDatasetUpload(ctx context.Context, req *connect.Request[v1.InitiateDatasetUploadRequest]) (*connect.Response[v1.InitiateDatasetUploadResponse], error) {
	return c.initiateDatasetUpload.CallUnary(ctx, req)
}

// CompleteDatasetUpload calls geoquerry.v1.GisIngestionService.CompleteDatasetUpload.
func (c *gisIngestionServiceClient) CompleteDatasetUpload(ctx context.Context, req *connect.Request[v1.CompleteDatasetUploadRequest]) (*connect.Response[v1.CompleteDatasetUploadResponse], error) {
	return c.completeDatasetUpload.CallUnary(ctx, req)
}

// GetDatasetStatus calls geoquerry.v1.GisIngestionService.GetDatasetStatus.
func (c *gisIngestionServiceClient) GetDatasetStatus(ctx context.Context, req *connect.Request[v1.GetDatasetStatusRequest]) (*connect.Response[v1.GetDatasetStatusResponse], error) {
	return c.getDatasetStatus.CallUnary(ctx, req)
}

// ListDatasets calls geoquerry.v1.GisIngestionService.ListDatasets.
func (c *gisIngestionServiceClient) ListDatasets(ctx context.Context, req *connect.Request[v1.ListDatasetsRequest]) (*connect.Response[v1.ListDatasetsResponse], error) {
	return c.listDatasets.CallUnary(ctx, req)
}

// GisIngestionServiceHandler is an implementation of the geoquerry.v1.GisIngestionService service.
type GisIngestionServiceHandler interface {
	// InitiateDatasetUpload generates a quarantine presigned PUT URL in Cloudflare R2.
	InitiateDatasetUpload(context.Context, *connect.Request[v1.InitiateDatasetUploadRequest]) (*connect.Response[v1.InitiateDatasetUploadResponse], error)
	// CompleteDatasetUpload notifies the backend that upload finished, enqueuing a sandboxed processing job.
	CompleteDatasetUpload(context.Context, *connect.Request[v1.CompleteDatasetUploadRequest]) (*connect.Response[v1.CompleteDatasetUploadResponse], error)
	// GetDatasetStatus polls the ingestion state and extraction summary.
	GetDatasetStatus(context.Context, *connect.Request[v1.GetDatasetStatusRequest]) (*connect.Response[v1.GetDatasetStatusResponse], error)
	// ListDatasets returns verified spatial datasets for a project.
	ListDatasets(context.Context, *connect.Request[v1.ListDatasetsRequest]) (*connect.Response[v1.ListDatasetsResponse], error)
}

// NewGisIngestionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGisIngestionServiceHandler(svc GisIngestionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gisIngestionServiceMethods := v1.File_geoquerry_v1_gis_proto.Services().ByName("GisIngestionService").Methods()
	gisIngestionServiceInitiateDatasetUploadHandler := connect.NewUnaryHandler(
		GisIngestionServiceInitiateDatasetUploadProcedure,
		svc.InitiateDatasetUpload,
		connect.WithSchema(gisIngestionServiceMethods.ByName("InitiateDatasetUpload")),
		connect.WithHandlerOptions(opts...),
	)
	gisIngestionServiceCompleteDatasetUploadHandler := connect.NewUnaryHandler(
		GisIngestionServiceCompleteDatasetUploadProcedure,
		svc.CompleteDatasetUpload,
		connect.WithSchema(gisIngestionServiceMethods.ByName("CompleteDatasetUpload")),
		connect.WithHandlerOptions(opts...),
	)
	gisIngestionServiceGetDatasetStatusHandler := connect.NewUnaryHandler(
		GisIngestionServiceGetDatasetStatusProcedure,
		svc.GetDatasetStatus,
		connect.WithSchema(gisIngestionServiceMethods.ByName("GetDatasetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	gisIngestionServiceListDatasetsHandler := connect.NewUnaryHandler(
		GisIngestionServiceListDatasetsProcedure,
		svc.ListDatasets,
		connect.WithSchema(gisIngestionServiceMethods.ByName("ListDatasets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/geoquerry.v1.GisIngestionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GisIngestionServiceInitiateDatasetUploadProcedure:
			gisIngestionServiceInitiateDatasetUploadHandler.ServeHTTP(w, r)
		case GisIngestionServiceCompleteDatasetUploadProcedure:
			gisIngestionServiceCompleteDatasetUploadHandler.ServeHTTP(w, r)
		case GisIngestionServiceGetDatasetStatusProcedure:
			gisIngestionServiceGetDatasetStatusHandler.ServeHTTP(w, r)
		case GisIngestionServiceListDatasetsProcedure:
			gisIngestionServiceListDatasetsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGisIngestionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGisIngestionServiceHandler struct{}

func (UnimplementedGisIngestionServiceHandler) InitiateDatasetUpload(context.Context, *connect.Request[v1.InitiateDatasetUploadRequest]) (*connect.Response[v1.InitiateDatasetUploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.GisIngestionService.InitiateDatasetUpload is not implemented"))
}

func (UnimplementedGisIngestionServiceHandler) CompleteDatasetUpload(context.Context, *connect.Request[v1.CompleteDatasetUploadRequest]) (*connect.Response[v1.CompleteDatasetUploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.GisIngestionService.CompleteDatasetUpload is not implemented"))
}

func (UnimplementedGisIngestionServiceHandler) GetDatasetStatus(context.Context, *connect.Request[v1.GetDatasetStatusRequest]) (*connect.Response[v1.GetDatasetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.GisIngestionService.GetDatasetStatus is not implemented"))
}

func (UnimplementedGisIngestionServiceHandler) ListDatasets(context.Context, *connect.Request[v1.ListDatasetsRequest]) (*connect.Response[v1.ListDatasetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.GisIngestionService.ListDatasets is not implemented"))
}
