// client communication with go backend

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: geoquerry/v1/service.proto

package geoquerryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	geoquerryv1 "gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerryv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GeoquerrySyncServiceName is the fully-qualified name of the GeoquerrySyncService service.
	GeoquerrySyncServiceName = "geoquerry.v1.GeoquerrySyncService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GeoquerrySyncServicePushSyncQueueProcedure is the fully-qualified name of the
	// GeoquerrySyncService's PushSyncQueue RPC.
	GeoquerrySyncServicePushSyncQueueProcedure = "/geoquerry.v1.GeoquerrySyncService/PushSyncQueue"
	// GeoquerrySyncServicePullProjectDataProcedure is the fully-qualified name of the
	// GeoquerrySyncService's PullProjectData RPC.
	GeoquerrySyncServicePullProjectDataProcedure = "/geoquerry.v1.GeoquerrySyncService/PullProjectData"
	// GeoquerrySyncServiceStreamLiveTelemetryProcedure is the fully-qualified name of the
	// GeoquerrySyncService's StreamLiveTelemetry RPC.
	GeoquerrySyncServiceStreamLiveTelemetryProcedure = "/geoquerry.v1.GeoquerrySyncService/StreamLiveTelemetry"
)

// GeoquerrySyncServiceClient is a client for the geoquerry.v1.GeoquerrySyncService service.
type GeoquerrySyncServiceClient interface {
	PushSyncQueue(context.Context, *connect.Request[geoquerryv1.PushSyncQueueRequest]) (*connect.Response[geoquerryv1.PushSyncQueueResponse], error)
	PullProjectData(context.Context, *connect.Request[geoquerryv1.PullProjectDataRequest]) (*connect.Response[geoquerryv1.PullProjectDataResponse], error)
	StreamLiveTelemetry(context.Context) *connect.BidiStreamForClient[geoquerryv1.StreamLiveTelemetryRequest, geoquerryv1.StreamLiveTelemetryResponse]
}

// NewGeoquerrySyncServiceClient constructs a client for the geoquerry.v1.GeoquerrySyncService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGeoquerrySyncServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GeoquerrySyncServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	geoquerrySyncServiceMethods := geoquerryv1.File_geoquerry_v1_service_proto.Services().ByName("GeoquerrySyncService").Methods()
	return &geoquerrySyncServiceClient{
		pushSyncQueue: connect.NewClient[geoquerryv1.PushSyncQueueRequest, geoquerryv1.PushSyncQueueResponse](
			httpClient,
			baseURL+GeoquerrySyncServicePushSyncQueueProcedure,
			connect.WithSchema(geoquerrySyncServiceMethods.ByName("PushSyncQueue")),
			connect.WithClientOptions(opts...),
		),
		pullProjectData: connect.NewClient[geoquerryv1.PullProjectDataRequest, geoquerryv1.PullProjectDataResponse](
			httpClient,
			baseURL+GeoquerrySyncServicePullProjectDataProcedure,
			connect.WithSchema(geoquerrySyncServiceMethods.ByName("PullProjectData")),
			connect.WithClientOptions(opts...),
		),
		streamLiveTelemetry: connect.NewClient[geoquerryv1.StreamLiveTelemetryRequest, geoquerryv1.StreamLiveTelemetryResponse](
			httpClient,
			baseURL+GeoquerrySyncServiceStreamLiveTelemetryProcedure,
			connect.WithSchema(geoquerrySyncServiceMethods.ByName("StreamLiveTelemetry")),
			connect.WithClientOptions(opts...),
		),
	}
}

// geoquerrySyncServiceClient implements GeoquerrySyncServiceClient.
type geoquerrySyncServiceClient struct {
	pushSyncQueue       *connect.Client[geoquerryv1.PushSyncQueueRequest, geoquerryv1.PushSyncQueueResponse]
	pullProjectData     *connect.Client[geoquerryv1.PullProjectDataRequest, geoquerryv1.PullProjectDataResponse]
	streamLiveTelemetry *connect.Client[geoquerryv1.StreamLiveTelemetryRequest, geoquerryv1.StreamLiveTelemetryResponse]
}

// PushSyncQueue calls geoquerry.v1.GeoquerrySyncService.PushSyncQueue.
func (c *geoquerrySyncServiceClient) PushSyncQueue(ctx context.Context, req *connect.Request[geoquerryv1.PushSyncQueueRequest]) (*connect.Response[geoquerryv1.PushSyncQueueResponse], error) {
	return c.pushSyncQueue.CallUnary(ctx, req)
}

// PullProjectData calls geoquerry.v1.GeoquerrySyncService.PullProjectData.
func (c *geoquerrySyncServiceClient) PullProjectData(ctx context.Context, req *connect.Request[geoquerryv1.PullProjectDataRequest]) (*connect.Response[geoquerryv1.PullProjectDataResponse], error) {
	return c.pullProjectData.CallUnary(ctx, req)
}

// StreamLiveTelemetry calls geoquerry.v1.GeoquerrySyncService.StreamLiveTelemetry.
func (c *geoquerrySyncServiceClient) StreamLiveTelemetry(ctx context.Context) *connect.BidiStreamForClient[geoquerryv1.StreamLiveTelemetryRequest, geoquerryv1.StreamLiveTelemetryResponse] {
	return c.streamLiveTelemetry.CallBidiStream(ctx)
}

// GeoquerrySyncServiceHandler is an implementation of the geoquerry.v1.GeoquerrySyncService
// service.
type GeoquerrySyncServiceHandler interface {
	PushSyncQueue(context.Context, *connect.Request[geoquerryv1.PushSyncQueueRequest]) (*connect.Response[geoquerryv1.PushSyncQueueResponse], error)
	PullProjectData(context.Context, *connect.Request[geoquerryv1.PullProjectDataRequest]) (*connect.Response[geoquerryv1.PullProjectDataResponse], error)
	StreamLiveTelemetry(context.Context, *connect.BidiStream[geoquerryv1.StreamLiveTelemetryRequest, geoquerryv1.StreamLiveTelemetryResponse]) error
}

// NewGeoquerrySyncServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGeoquerrySyncServiceHandler(svc GeoquerrySyncServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	geoquerrySyncServiceMethods := geoquerryv1.File_geoquerry_v1_service_proto.Services().ByName("GeoquerrySyncService").Methods()
	geoquerrySyncServicePushSyncQueueHandler := connect.NewUnaryHandler(
		GeoquerrySyncServicePushSyncQueueProcedure,
		svc.PushSyncQueue,
		connect.WithSchema(geoquerrySyncServiceMethods.ByName("PushSyncQueue")),
		connect.WithHandlerOptions(opts...),
	)
	geoquerrySyncServicePullProjectDataHandler := connect.NewUnaryHandler(
		GeoquerrySyncServicePullProjectDataProcedure,
		svc.PullProjectData,
		connect.WithSchema(geoquerrySyncServiceMethods.ByName("PullProjectData")),
		connect.WithHandlerOptions(opts...),
	)
	geoquerrySyncServiceStreamLiveTelemetryHandler := connect.NewBidiStreamHandler(
		GeoquerrySyncServiceStreamLiveTelemetryProcedure,
		svc.StreamLiveTelemetry,
		connect.WithSchema(geoquerrySyncServiceMethods.ByName("StreamLiveTelemetry")),
		connect.WithHandlerOptions(opts...),
	)
	return "/geoquerry.v1.GeoquerrySyncService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GeoquerrySyncServicePushSyncQueueProcedure:
			geoquerrySyncServicePushSyncQueueHandler.ServeHTTP(w, r)
		case GeoquerrySyncServicePullProjectDataProcedure:
			geoquerrySyncServicePullProjectDataHandler.ServeHTTP(w, r)
		case GeoquerrySyncServiceStreamLiveTelemetryProcedure:
			geoquerrySyncServiceStreamLiveTelemetryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGeoquerrySyncServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGeoquerrySyncServiceHandler struct{}

func (UnimplementedGeoquerrySyncServiceHandler) PushSyncQueue(context.Context, *connect.Request[geoquerryv1.PushSyncQueueRequest]) (*connect.Response[geoquerryv1.PushSyncQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.GeoquerrySyncService.PushSyncQueue is not implemented"))
}

func (UnimplementedGeoquerrySyncServiceHandler) PullProjectData(context.Context, *connect.Request[geoquerryv1.PullProjectDataRequest]) (*connect.Response[geoquerryv1.PullProjectDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.GeoquerrySyncService.PullProjectData is not implemented"))
}

func (UnimplementedGeoquerrySyncServiceHandler) StreamLiveTelemetry(context.Context, *connect.BidiStream[geoquerryv1.StreamLiveTelemetryRequest, geoquerryv1.StreamLiveTelemetryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.GeoquerrySyncService.StreamLiveTelemetry is not implemented"))
}
