// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: geoquerry/v1/telemetry.proto

package geoquerryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelemetryServiceName is the fully-qualified name of the TelemetryService service.
	TelemetryServiceName = "geoquerry.v1.TelemetryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelemetryServiceAcquireStreamTicketProcedure is the fully-qualified name of the
	// TelemetryService's AcquireStreamTicket RPC.
	TelemetryServiceAcquireStreamTicketProcedure = "/geoquerry.v1.TelemetryService/AcquireStreamTicket"
	// TelemetryServiceStreamLiveTelemetryProcedure is the fully-qualified name of the
	// TelemetryService's StreamLiveTelemetry RPC.
	TelemetryServiceStreamLiveTelemetryProcedure = "/geoquerry.v1.TelemetryService/StreamLiveTelemetry"
)

// TelemetryServiceClient is a client for the geoquerry.v1.TelemetryService service.
type TelemetryServiceClient interface {
	AcquireStreamTicket(context.Context, *connect.Request[v1.StreamTicketRequest]) (*connect.Response[v1.StreamTicketResponse], error)
	StreamLiveTelemetry(context.Context) *connect.BidiStreamForClient[v1.StreamLiveTelemetryRequest, v1.StreamLiveTelemetryResponse]
}

// NewTelemetryServiceClient constructs a client for the geoquerry.v1.TelemetryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelemetryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelemetryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telemetryServiceMethods := v1.File_geoquerry_v1_telemetry_proto.Services().ByName("TelemetryService").Methods()
	return &telemetryServiceClient{
		acquireStreamTicket: connect.NewClient[v1.StreamTicketRequest, v1.StreamTicketResponse](
			httpClient,
			baseURL+TelemetryServiceAcquireStreamTicketProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("AcquireStreamTicket")),
			connect.WithClientOptions(opts...),
		),
		streamLiveTelemetry: connect.NewClient[v1.StreamLiveTelemetryRequest, v1.StreamLiveTelemetryResponse](
			httpClient,
			baseURL+TelemetryServiceStreamLiveTelemetryProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("StreamLiveTelemetry")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telemetryServiceClient implements TelemetryServiceClient.
type telemetryServiceClient struct {
	acquireStreamTicket *connect.Client[v1.StreamTicketRequest, v1.StreamTicketResponse]
	streamLiveTelemetry *connect.Client[v1.StreamLiveTelemetryRequest, v1.StreamLiveTelemetryResponse]
}

// AcquireStreamTicket calls geoquerry.v1.TelemetryService.AcquireStreamTicket.
func (c *telemetryServiceClient) AcquireStreamTicket(ctx context.Context, req *connect.Request[v1.StreamTicketRequest]) (*connect.Response[v1.StreamTicketResponse], error) {
	return c.acquireStreamTicket.CallUnary(ctx, req)
}

// StreamLiveTelemetry calls geoquerry.v1.TelemetryService.StreamLiveTelemetry.
func (c *telemetryServiceClient) StreamLiveTelemetry(ctx context.Context) *connect.BidiStreamForClient[v1.StreamLiveTelemetryRequest, v1.StreamLiveTelemetryResponse] {
	return c.streamLiveTelemetry.CallBidiStream(ctx)
}

// TelemetryServiceHandler is an implementation of the geoquerry.v1.TelemetryService service.
type TelemetryServiceHandler interface {
	AcquireStreamTicket(context.Context, *connect.Request[v1.StreamTicketRequest]) (*connect.Response[v1.StreamTicketResponse], error)
	StreamLiveTelemetry(context.Context, *connect.BidiStream[v1.StreamLiveTelemetryRequest, v1.StreamLiveTelemetryResponse]) error
}

// NewTelemetryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelemetryServiceHandler(svc TelemetryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telemetryServiceMethods := v1.File_geoquerry_v1_telemetry_proto.Services().ByName("TelemetryService").Methods()
	telemetryServiceAcquireStreamTicketHandler := connect.NewUnaryHandler(
		TelemetryServiceAcquireStreamTicketProcedure,
		svc.AcquireStreamTicket,
		connect.WithSchema(telemetryServiceMethods.ByName("AcquireStreamTicket")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceStreamLiveTelemetryHandler := connect.NewBidiStreamHandler(
		TelemetryServiceStreamLiveTelemetryProcedure,
		svc.StreamLiveTelemetry,
		connect.WithSchema(telemetryServiceMethods.ByName("StreamLiveTelemetry")),
		connect.WithHandlerOptions(opts...),
	)
	return "/geoquerry.v1.TelemetryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelemetryServiceAcquireStreamTicketProcedure:
			telemetryServiceAcquireStreamTicketHandler.ServeHTTP(w, r)
		case TelemetryServiceStreamLiveTelemetryProcedure:
			telemetryServiceStreamLiveTelemetryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelemetryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelemetryServiceHandler struct{}

func (UnimplementedTelemetryServiceHandler) AcquireStreamTicket(context.Context, *connect.Request[v1.StreamTicketRequest]) (*connect.Response[v1.StreamTicketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TelemetryService.AcquireStreamTicket is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) StreamLiveTelemetry(context.Context, *connect.BidiStream[v1.StreamLiveTelemetryRequest, v1.StreamLiveTelemetryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TelemetryService.StreamLiveTelemetry is not implemented"))
}
