// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: geoquerry/v1/tenant.proto

package geoquerryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TenantServiceName is the fully-qualified name of the TenantService service.
	TenantServiceName = "geoquerry.v1.TenantService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TenantServiceListOrganizationsProcedure is the fully-qualified name of the TenantService's
	// ListOrganizations RPC.
	TenantServiceListOrganizationsProcedure = "/geoquerry.v1.TenantService/ListOrganizations"
	// TenantServiceGetOrganizationProcedure is the fully-qualified name of the TenantService's
	// GetOrganization RPC.
	TenantServiceGetOrganizationProcedure = "/geoquerry.v1.TenantService/GetOrganization"
	// TenantServiceCreateOrganizationProcedure is the fully-qualified name of the TenantService's
	// CreateOrganization RPC.
	TenantServiceCreateOrganizationProcedure = "/geoquerry.v1.TenantService/CreateOrganization"
	// TenantServiceUpdateOrganizationProcedure is the fully-qualified name of the TenantService's
	// UpdateOrganization RPC.
	TenantServiceUpdateOrganizationProcedure = "/geoquerry.v1.TenantService/UpdateOrganization"
	// TenantServiceTransferOrganizationOwnershipProcedure is the fully-qualified name of the
	// TenantService's TransferOrganizationOwnership RPC.
	TenantServiceTransferOrganizationOwnershipProcedure = "/geoquerry.v1.TenantService/TransferOrganizationOwnership"
	// TenantServiceListMembersProcedure is the fully-qualified name of the TenantService's ListMembers
	// RPC.
	TenantServiceListMembersProcedure = "/geoquerry.v1.TenantService/ListMembers"
	// TenantServiceInviteMemberProcedure is the fully-qualified name of the TenantService's
	// InviteMember RPC.
	TenantServiceInviteMemberProcedure = "/geoquerry.v1.TenantService/InviteMember"
	// TenantServiceUpdateMemberRoleProcedure is the fully-qualified name of the TenantService's
	// UpdateMemberRole RPC.
	TenantServiceUpdateMemberRoleProcedure = "/geoquerry.v1.TenantService/UpdateMemberRole"
	// TenantServiceRemoveMemberProcedure is the fully-qualified name of the TenantService's
	// RemoveMember RPC.
	TenantServiceRemoveMemberProcedure = "/geoquerry.v1.TenantService/RemoveMember"
	// TenantServiceListProjectsProcedure is the fully-qualified name of the TenantService's
	// ListProjects RPC.
	TenantServiceListProjectsProcedure = "/geoquerry.v1.TenantService/ListProjects"
	// TenantServiceGetProjectProcedure is the fully-qualified name of the TenantService's GetProject
	// RPC.
	TenantServiceGetProjectProcedure = "/geoquerry.v1.TenantService/GetProject"
	// TenantServiceCreateProjectProcedure is the fully-qualified name of the TenantService's
	// CreateProject RPC.
	TenantServiceCreateProjectProcedure = "/geoquerry.v1.TenantService/CreateProject"
	// TenantServiceUpdateProjectProcedure is the fully-qualified name of the TenantService's
	// UpdateProject RPC.
	TenantServiceUpdateProjectProcedure = "/geoquerry.v1.TenantService/UpdateProject"
	// TenantServiceDeleteProjectProcedure is the fully-qualified name of the TenantService's
	// DeleteProject RPC.
	TenantServiceDeleteProjectProcedure = "/geoquerry.v1.TenantService/DeleteProject"
)

// TenantServiceClient is a client for the geoquerry.v1.TenantService service.
type TenantServiceClient interface {
	// Organization operations
	ListOrganizations(context.Context, *connect.Request[v1.ListOrganizationsRequest]) (*connect.Response[v1.ListOrganizationsResponse], error)
	GetOrganization(context.Context, *connect.Request[v1.GetOrganizationRequest]) (*connect.Response[v1.GetOrganizationResponse], error)
	CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error)
	UpdateOrganization(context.Context, *connect.Request[v1.UpdateOrganizationRequest]) (*connect.Response[v1.UpdateOrganizationResponse], error)
	TransferOrganizationOwnership(context.Context, *connect.Request[v1.TransferOrganizationOwnershipRequest]) (*connect.Response[v1.TransferOrganizationOwnershipResponse], error)
	// Membership operations
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	InviteMember(context.Context, *connect.Request[v1.InviteMemberRequest]) (*connect.Response[v1.InviteMemberResponse], error)
	UpdateMemberRole(context.Context, *connect.Request[v1.UpdateMemberRoleRequest]) (*connect.Response[v1.UpdateMemberRoleResponse], error)
	RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error)
	// Project operations
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error)
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error)
}

// NewTenantServiceClient constructs a client for the geoquerry.v1.TenantService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTenantServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TenantServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tenantServiceMethods := v1.File_geoquerry_v1_tenant_proto.Services().ByName("TenantService").Methods()
	return &tenantServiceClient{
		listOrganizations: connect.NewClient[v1.ListOrganizationsRequest, v1.ListOrganizationsResponse](
			httpClient,
			baseURL+TenantServiceListOrganizationsProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("ListOrganizations")),
			connect.WithClientOptions(opts...),
		),
		getOrganization: connect.NewClient[v1.GetOrganizationRequest, v1.GetOrganizationResponse](
			httpClient,
			baseURL+TenantServiceGetOrganizationProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("GetOrganization")),
			connect.WithClientOptions(opts...),
		),
		createOrganization: connect.NewClient[v1.CreateOrganizationRequest, v1.CreateOrganizationResponse](
			httpClient,
			baseURL+TenantServiceCreateOrganizationProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("CreateOrganization")),
			connect.WithClientOptions(opts...),
		),
		updateOrganization: connect.NewClient[v1.UpdateOrganizationRequest, v1.UpdateOrganizationResponse](
			httpClient,
			baseURL+TenantServiceUpdateOrganizationProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("UpdateOrganization")),
			connect.WithClientOptions(opts...),
		),
		transferOrganizationOwnership: connect.NewClient[v1.TransferOrganizationOwnershipRequest, v1.TransferOrganizationOwnershipResponse](
			httpClient,
			baseURL+TenantServiceTransferOrganizationOwnershipProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("TransferOrganizationOwnership")),
			connect.WithClientOptions(opts...),
		),
		listMembers: connect.NewClient[v1.ListMembersRequest, v1.ListMembersResponse](
			httpClient,
			baseURL+TenantServiceListMembersProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("ListMembers")),
			connect.WithClientOptions(opts...),
		),
		inviteMember: connect.NewClient[v1.InviteMemberRequest, v1.InviteMemberResponse](
			httpClient,
			baseURL+TenantServiceInviteMemberProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("InviteMember")),
			connect.WithClientOptions(opts...),
		),
		updateMemberRole: connect.NewClient[v1.UpdateMemberRoleRequest, v1.UpdateMemberRoleResponse](
			httpClient,
			baseURL+TenantServiceUpdateMemberRoleProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("UpdateMemberRole")),
			connect.WithClientOptions(opts...),
		),
		removeMember: connect.NewClient[v1.RemoveMemberRequest, v1.RemoveMemberResponse](
			httpClient,
			baseURL+TenantServiceRemoveMemberProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("RemoveMember")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+TenantServiceListProjectsProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		getProject: connect.NewClient[v1.GetProjectRequest, v1.GetProjectResponse](
			httpClient,
			baseURL+TenantServiceGetProjectProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("GetProject")),
			connect.WithClientOptions(opts...),
		),
		createProject: connect.NewClient[v1.CreateProjectRequest, v1.CreateProjectResponse](
			httpClient,
			baseURL+TenantServiceCreateProjectProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		updateProject: connect.NewClient[v1.UpdateProjectRequest, v1.UpdateProjectResponse](
			httpClient,
			baseURL+TenantServiceUpdateProjectProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("UpdateProject")),
			connect.WithClientOptions(opts...),
		),
		deleteProject: connect.NewClient[v1.DeleteProjectRequest, v1.DeleteProjectResponse](
			httpClient,
			baseURL+TenantServiceDeleteProjectProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("DeleteProject")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tenantServiceClient implements TenantServiceClient.
type tenantServiceClient struct {
	listOrganizations             *connect.Client[v1.ListOrganizationsRequest, v1.ListOrganizationsResponse]
	getOrganization               *connect.Client[v1.GetOrganizationRequest, v1.GetOrganizationResponse]
	createOrganization            *connect.Client[v1.CreateOrganizationRequest, v1.CreateOrganizationResponse]
	updateOrganization            *connect.Client[v1.UpdateOrganizationRequest, v1.UpdateOrganizationResponse]
	transferOrganizationOwnership *connect.Client[v1.TransferOrganizationOwnershipRequest, v1.TransferOrganizationOwnershipResponse]
	listMembers                   *connect.Client[v1.ListMembersRequest, v1.ListMembersResponse]
	inviteMember                  *connect.Client[v1.InviteMemberRequest, v1.InviteMemberResponse]
	updateMemberRole              *connect.Client[v1.UpdateMemberRoleRequest, v1.UpdateMemberRoleResponse]
	removeMember                  *connect.Client[v1.RemoveMemberRequest, v1.RemoveMemberResponse]
	listProjects                  *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	getProject                    *connect.Client[v1.GetProjectRequest, v1.GetProjectResponse]
	createProject                 *connect.Client[v1.CreateProjectRequest, v1.CreateProjectResponse]
	updateProject                 *connect.Client[v1.UpdateProjectRequest, v1.UpdateProjectResponse]
	deleteProject                 *connect.Client[v1.DeleteProjectRequest, v1.DeleteProjectResponse]
}

// ListOrganizations calls geoquerry.v1.TenantService.ListOrganizations.
func (c *tenantServiceClient) ListOrganizations(ctx context.Context, req *connect.Request[v1.ListOrganizationsRequest]) (*connect.Response[v1.ListOrganizationsResponse], error) {
	return c.listOrganizations.CallUnary(ctx, req)
}

// GetOrganization calls geoquerry.v1.TenantService.GetOrganization.
func (c *tenantServiceClient) GetOrganization(ctx context.Context, req *connect.Request[v1.GetOrganizationRequest]) (*connect.Response[v1.GetOrganizationResponse], error) {
	return c.getOrganization.CallUnary(ctx, req)
}

// CreateOrganization calls geoquerry.v1.TenantService.CreateOrganization.
func (c *tenantServiceClient) CreateOrganization(ctx context.Context, req *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error) {
	return c.createOrganization.CallUnary(ctx, req)
}

// UpdateOrganization calls geoquerry.v1.TenantService.UpdateOrganization.
func (c *tenantServiceClient) UpdateOrganization(ctx context.Context, req *connect.Request[v1.UpdateOrganizationRequest]) (*connect.Response[v1.UpdateOrganizationResponse], error) {
	return c.updateOrganization.CallUnary(ctx, req)
}

// TransferOrganizationOwnership calls geoquerry.v1.TenantService.TransferOrganizationOwnership.
func (c *tenantServiceClient) TransferOrganizationOwnership(ctx context.Context, req *connect.Request[v1.TransferOrganizationOwnershipRequest]) (*connect.Response[v1.TransferOrganizationOwnershipResponse], error) {
	return c.transferOrganizationOwnership.CallUnary(ctx, req)
}

// ListMembers calls geoquerry.v1.TenantService.ListMembers.
func (c *tenantServiceClient) ListMembers(ctx context.Context, req *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// InviteMember calls geoquerry.v1.TenantService.InviteMember.
func (c *tenantServiceClient) InviteMember(ctx context.Context, req *connect.Request[v1.InviteMemberRequest]) (*connect.Response[v1.InviteMemberResponse], error) {
	return c.inviteMember.CallUnary(ctx, req)
}

// UpdateMemberRole calls geoquerry.v1.TenantService.UpdateMemberRole.
func (c *tenantServiceClient) UpdateMemberRole(ctx context.Context, req *connect.Request[v1.UpdateMemberRoleRequest]) (*connect.Response[v1.UpdateMemberRoleResponse], error) {
	return c.updateMemberRole.CallUnary(ctx, req)
}

// RemoveMember calls geoquerry.v1.TenantService.RemoveMember.
func (c *tenantServiceClient) RemoveMember(ctx context.Context, req *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error) {
	return c.removeMember.CallUnary(ctx, req)
}

// ListProjects calls geoquerry.v1.TenantService.ListProjects.
func (c *tenantServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// GetProject calls geoquerry.v1.TenantService.GetProject.
func (c *tenantServiceClient) GetProject(ctx context.Context, req *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// CreateProject calls geoquerry.v1.TenantService.CreateProject.
func (c *tenantServiceClient) CreateProject(ctx context.Context, req *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// UpdateProject calls geoquerry.v1.TenantService.UpdateProject.
func (c *tenantServiceClient) UpdateProject(ctx context.Context, req *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return c.updateProject.CallUnary(ctx, req)
}

// DeleteProject calls geoquerry.v1.TenantService.DeleteProject.
func (c *tenantServiceClient) DeleteProject(ctx context.Context, req *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error) {
	return c.deleteProject.CallUnary(ctx, req)
}

// TenantServiceHandler is an implementation of the geoquerry.v1.TenantService service.
type TenantServiceHandler interface {
	// Organization operations
	ListOrganizations(context.Context, *connect.Request[v1.ListOrganizationsRequest]) (*connect.Response[v1.ListOrganizationsResponse], error)
	GetOrganization(context.Context, *connect.Request[v1.GetOrganizationRequest]) (*connect.Response[v1.GetOrganizationResponse], error)
	CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error)
	UpdateOrganization(context.Context, *connect.Request[v1.UpdateOrganizationRequest]) (*connect.Response[v1.UpdateOrganizationResponse], error)
	TransferOrganizationOwnership(context.Context, *connect.Request[v1.TransferOrganizationOwnershipRequest]) (*connect.Response[v1.TransferOrganizationOwnershipResponse], error)
	// Membership operations
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	InviteMember(context.Context, *connect.Request[v1.InviteMemberRequest]) (*connect.Response[v1.InviteMemberResponse], error)
	UpdateMemberRole(context.Context, *connect.Request[v1.UpdateMemberRoleRequest]) (*connect.Response[v1.UpdateMemberRoleResponse], error)
	RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error)
	// Project operations
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error)
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error)
}

// NewTenantServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTenantServiceHandler(svc TenantServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tenantServiceMethods := v1.File_geoquerry_v1_tenant_proto.Services().ByName("TenantService").Methods()
	tenantServiceListOrganizationsHandler := connect.NewUnaryHandler(
		TenantServiceListOrganizationsProcedure,
		svc.ListOrganizations,
		connect.WithSchema(tenantServiceMethods.ByName("ListOrganizations")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceGetOrganizationHandler := connect.NewUnaryHandler(
		TenantServiceGetOrganizationProcedure,
		svc.GetOrganization,
		connect.WithSchema(tenantServiceMethods.ByName("GetOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceCreateOrganizationHandler := connect.NewUnaryHandler(
		TenantServiceCreateOrganizationProcedure,
		svc.CreateOrganization,
		connect.WithSchema(tenantServiceMethods.ByName("CreateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceUpdateOrganizationHandler := connect.NewUnaryHandler(
		TenantServiceUpdateOrganizationProcedure,
		svc.UpdateOrganization,
		connect.WithSchema(tenantServiceMethods.ByName("UpdateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceTransferOrganizationOwnershipHandler := connect.NewUnaryHandler(
		TenantServiceTransferOrganizationOwnershipProcedure,
		svc.TransferOrganizationOwnership,
		connect.WithSchema(tenantServiceMethods.ByName("TransferOrganizationOwnership")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceListMembersHandler := connect.NewUnaryHandler(
		TenantServiceListMembersProcedure,
		svc.ListMembers,
		connect.WithSchema(tenantServiceMethods.ByName("ListMembers")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceInviteMemberHandler := connect.NewUnaryHandler(
		TenantServiceInviteMemberProcedure,
		svc.InviteMember,
		connect.WithSchema(tenantServiceMethods.ByName("InviteMember")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceUpdateMemberRoleHandler := connect.NewUnaryHandler(
		TenantServiceUpdateMemberRoleProcedure,
		svc.UpdateMemberRole,
		connect.WithSchema(tenantServiceMethods.ByName("UpdateMemberRole")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceRemoveMemberHandler := connect.NewUnaryHandler(
		TenantServiceRemoveMemberProcedure,
		svc.RemoveMember,
		connect.WithSchema(tenantServiceMethods.ByName("RemoveMember")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceListProjectsHandler := connect.NewUnaryHandler(
		TenantServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(tenantServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceGetProjectHandler := connect.NewUnaryHandler(
		TenantServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(tenantServiceMethods.ByName("GetProject")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceCreateProjectHandler := connect.NewUnaryHandler(
		TenantServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(tenantServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceUpdateProjectHandler := connect.NewUnaryHandler(
		TenantServiceUpdateProjectProcedure,
		svc.UpdateProject,
		connect.WithSchema(tenantServiceMethods.ByName("UpdateProject")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceDeleteProjectHandler := connect.NewUnaryHandler(
		TenantServiceDeleteProjectProcedure,
		svc.DeleteProject,
		connect.WithSchema(tenantServiceMethods.ByName("DeleteProject")),
		connect.WithHandlerOptions(opts...),
	)
	return "/geoquerry.v1.TenantService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TenantServiceListOrganizationsProcedure:
			tenantServiceListOrganizationsHandler.ServeHTTP(w, r)
		case TenantServiceGetOrganizationProcedure:
			tenantServiceGetOrganizationHandler.ServeHTTP(w, r)
		case TenantServiceCreateOrganizationProcedure:
			tenantServiceCreateOrganizationHandler.ServeHTTP(w, r)
		case TenantServiceUpdateOrganizationProcedure:
			tenantServiceUpdateOrganizationHandler.ServeHTTP(w, r)
		case TenantServiceTransferOrganizationOwnershipProcedure:
			tenantServiceTransferOrganizationOwnershipHandler.ServeHTTP(w, r)
		case TenantServiceListMembersProcedure:
			tenantServiceListMembersHandler.ServeHTTP(w, r)
		case TenantServiceInviteMemberProcedure:
			tenantServiceInviteMemberHandler.ServeHTTP(w, r)
		case TenantServiceUpdateMemberRoleProcedure:
			tenantServiceUpdateMemberRoleHandler.ServeHTTP(w, r)
		case TenantServiceRemoveMemberProcedure:
			tenantServiceRemoveMemberHandler.ServeHTTP(w, r)
		case TenantServiceListProjectsProcedure:
			tenantServiceListProjectsHandler.ServeHTTP(w, r)
		case TenantServiceGetProjectProcedure:
			tenantServiceGetProjectHandler.ServeHTTP(w, r)
		case TenantServiceCreateProjectProcedure:
			tenantServiceCreateProjectHandler.ServeHTTP(w, r)
		case TenantServiceUpdateProjectProcedure:
			tenantServiceUpdateProjectHandler.ServeHTTP(w, r)
		case TenantServiceDeleteProjectProcedure:
			tenantServiceDeleteProjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTenantServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTenantServiceHandler struct{}

func (UnimplementedTenantServiceHandler) ListOrganizations(context.Context, *connect.Request[v1.ListOrganizationsRequest]) (*connect.Response[v1.ListOrganizationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.ListOrganizations is not implemented"))
}

func (UnimplementedTenantServiceHandler) GetOrganization(context.Context, *connect.Request[v1.GetOrganizationRequest]) (*connect.Response[v1.GetOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.GetOrganization is not implemented"))
}

func (UnimplementedTenantServiceHandler) CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.CreateOrganization is not implemented"))
}

func (UnimplementedTenantServiceHandler) UpdateOrganization(context.Context, *connect.Request[v1.UpdateOrganizationRequest]) (*connect.Response[v1.UpdateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.UpdateOrganization is not implemented"))
}

func (UnimplementedTenantServiceHandler) TransferOrganizationOwnership(context.Context, *connect.Request[v1.TransferOrganizationOwnershipRequest]) (*connect.Response[v1.TransferOrganizationOwnershipResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.TransferOrganizationOwnership is not implemented"))
}

func (UnimplementedTenantServiceHandler) ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.ListMembers is not implemented"))
}

func (UnimplementedTenantServiceHandler) InviteMember(context.Context, *connect.Request[v1.InviteMemberRequest]) (*connect.Response[v1.InviteMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.InviteMember is not implemented"))
}

func (UnimplementedTenantServiceHandler) UpdateMemberRole(context.Context, *connect.Request[v1.UpdateMemberRoleRequest]) (*connect.Response[v1.UpdateMemberRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.UpdateMemberRole is not implemented"))
}

func (UnimplementedTenantServiceHandler) RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.RemoveMember is not implemented"))
}

func (UnimplementedTenantServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.ListProjects is not implemented"))
}

func (UnimplementedTenantServiceHandler) GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.GetProject is not implemented"))
}

func (UnimplementedTenantServiceHandler) CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.CreateProject is not implemented"))
}

func (UnimplementedTenantServiceHandler) UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.UpdateProject is not implemented"))
}

func (UnimplementedTenantServiceHandler) DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geoquerry.v1.TenantService.DeleteProject is not implemented"))
}
