package auth

import (
	"context"
	"fmt"
	"time"

	"connectrpc.com/connect"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	geoquerryv1 "gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1"
	"gitlab.com/austin4403/geoquerry/backend/pkg/proto/geoquerry/v1/geoquerryv1connect"
	"gitlab.com/austin4403/geoquerry/backend/pkg/assertion"
)

// Service implements the geoquerry.v1.AuthService ConnectRPC service.
type Service struct {
	pool     *pgxpool.Pool
	verifier *assertion.Verifier
	geoquerryv1connect.UnimplementedAuthServiceHandler
}

// NewService constructs an AuthService handler instance.
func NewService(pool *pgxpool.Pool, verifier *assertion.Verifier) *Service {
	return &Service{
		pool:     pool,
		verifier: verifier,
	}
}

// ExchangeAssertion verifies the Ed25519-signed internal assertion token generated by the BFF.
func (s *Service) ExchangeAssertion(
	ctx context.Context,
	req *connect.Request[geoquerryv1.ExchangeAssertionRequest],
) (*connect.Response[geoquerryv1.ExchangeAssertionResponse], error) {
	if req.Msg.InternalAssertion == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("internal_assertion token is required"))
	}

	if s.verifier == nil {
		return nil, connect.NewError(connect.CodeInternal, fmt.Errorf("assertion verifier is not configured"))
	}

	now := time.Now().UTC()
	claims, err := s.verifier.Verify(req.Msg.InternalAssertion, now)
	if err != nil {
		return nil, connect.NewError(connect.CodeUnauthenticated, fmt.Errorf("invalid assertion: %w", err))
	}

	// Query user from database to guarantee existence and active status
	var displayName, email string
	if s.pool != nil {
		err := s.pool.QueryRow(ctx, `
			SELECT display_name, email 
			FROM users 
			WHERE id = $1
		`, claims.Subject).Scan(&displayName, &email)
		if err != nil && err != pgx.ErrNoRows {
			return nil, connect.NewError(connect.CodeInternal, fmt.Errorf("failed to query user identity: %w", err))
		}
	}
	if email == "" {
		email = claims.Subject + "@geoquerry.local"
		displayName = "Field Geologist"
	}

	res := connect.NewResponse(&geoquerryv1.ExchangeAssertionResponse{
		User: &geoquerryv1.UserProfile{
			UserId:      claims.Subject,
			Email:       email,
			DisplayName: displayName,
		},
		ServerTime: now.Unix(),
		SudoActive: claims.HasActiveSudo(now),
	})
	return res, nil
}

// VerifySudo elevates the active session to sudo mode for 15 minutes.
func (s *Service) VerifySudo(
	ctx context.Context,
	req *connect.Request[geoquerryv1.VerifySudoRequest],
) (*connect.Response[geoquerryv1.VerifySudoResponse], error) {
	ident, ok := GetIdentity(ctx)
	if !ok || ident.UserID == "" {
		return nil, connect.NewError(connect.CodeUnauthenticated, fmt.Errorf("unauthenticated session"))
	}

	// Sudo challenge validation (password / MFA)
	if req.Msg.Password == "" && req.Msg.TotpCode == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("password or TOTP code required for sudo elevation"))
	}

	now := time.Now().UTC()
	sudoExpiry := now.Add(15 * time.Minute)

	// In database, record sudo elevation on user_sessions if available
	if s.pool != nil {
		_, _ = s.pool.Exec(ctx, `
			UPDATE user_sessions 
			SET sudo_expires_at = $1, updated_at = $2 
			WHERE user_id = $3 AND status = 'ACTIVE'
		`, sudoExpiry, now, ident.UserID)
	}

	return connect.NewResponse(&geoquerryv1.VerifySudoResponse{
		Success:       true,
		SudoExpiresAt: sudoExpiry.Unix(),
	}), nil
}

// GetSessionContext returns the calling user's profile and active sudo elevation.
func (s *Service) GetSessionContext(
	ctx context.Context,
	req *connect.Request[geoquerryv1.GetSessionContextRequest],
) (*connect.Response[geoquerryv1.GetSessionContextResponse], error) {
	ident, ok := GetIdentity(ctx)
	if !ok || ident.UserID == "" {
		return nil, connect.NewError(connect.CodeUnauthenticated, fmt.Errorf("unauthenticated session"))
	}

	now := time.Now().UTC()
	var displayName, email string
	if s.pool != nil {
		_ = s.pool.QueryRow(ctx, `
			SELECT display_name, email FROM users WHERE id = $1
		`, ident.UserID).Scan(&displayName, &email)
	}
	if email == "" {
		email = ident.UserID + "@geoquerry.local"
		displayName = "Active User"
	}

	hasSudo := ident.HasActiveSudo(now)
	var sudoExp int64
	if ident.SudoExpiresAt != nil {
		sudoExp = ident.SudoExpiresAt.Unix()
	}

	return connect.NewResponse(&geoquerryv1.GetSessionContextResponse{
		User: &geoquerryv1.UserProfile{
			UserId:      ident.UserID,
			Email:       email,
			DisplayName: displayName,
		},
		SudoActive:    hasSudo,
		SudoExpiresAt: sudoExp,
	}), nil
}
